### ISSUE TITLE
:enc<utf8-c8> on Proc appears to drop a lot of content

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2158]
As you can see from the output, when `:enc<utf8-c8>` is set on a `Proc` itself, only about 10% of content gets through. The same is not observed when using `latin1` encoding, or slurping from the `Proc` in binary and *then* decoding to `utf8-c8`

```
$ perl6 -e 'run("curl", :enc<utf8-c8>, :out, "-s", "https://www.google.com").out.slurp.chars.say'
1792

$ perl6 -e 'run("curl", :enc<latin1>, :out, "-s", "https://www.google.com").out.slurp.chars.say'
11288

$ perl6 -e 'run("curl", :out, "-s", "https://www.google.com").out.slurp(:bin).decode("utf8-c8").chars.say'
11263

$ perl6 -v
This is Rakudo version 2018.06-146-g1b3dd35 built on MoarVM version 2018.06-141-gcae4731
implementing Perl 6.c.
```

**Comment by AlexDaniel** [comment]
FWIW that used to work in the past. Bisected to (2017-09-10) https://github.com/rakudo/rakudo/commit/9b42484a5d0ca6b5d340620cc5d8dd88e2eb331f

**Comment by MasterDuke17** [comment]
Reverting https://github.com/MoarVM/MoarVM/pull/631 (the last four MoarVM commits pulled in from the bump bisected to above) fixes this, but I haven't yet been able to do any figuring out of why.

**Comment by MasterDuke17** [comment]
Valgrind output, @dogbert17++
```
================================================================================================
This is Rakudo Perl 6 running in valgrind, a tool for debugging and profiling programs.
Running a program in valgrind usually takes *a lot* more time than running it directly,
so please be patient.
Valgrind options can be added with MVM_VALGRIND_OPTS environment variable.

This Rakudo version is 2018.06.318.gcd.43.c.4.f.15 built on MoarVM version 2018.06.347.gca.0.ece.596,
running on arch (4.17.3.1.arch) / linux (4.17.11.arch.1)
------------------------------------------------------------------------------------------------
==31827== Memcheck, a memory error detector
==31827== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==31827== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==31827== Command: /home/dan/Source/perl6/install/bin/moar --execname=/home/dan/Source/perl6/install/bin/perl6-valgrind-m --libpath=/home/dan/Source/perl6/install/share/nqp/lib --libpath=/home/dan/Source/perl6/install/share/perl6/lib --libpath=/home/dan/Source/perl6/install/share/perl6/runtime /home/dan/Source/perl6/install/share/perl6/runtime/perl6.moarvm -e run("curl",\ :enc\<utf8-c8\>,\ :out,\ "-s",\ "https://www.google.com").out.slurp.chars.say
==31827== 
==31827== Invalid write of size 4
==31827==    at 0x50C67C3: append_grapheme (utf8_c8.c:209)
==31827==    by 0x50C56DC: process_bad_bytes (utf8_c8.c:298)
==31827==    by 0x50C5CAD: MVM_string_utf8_c8_decodestream (utf8_c8.c:559)
==31827==    by 0x50C04E7: run_decode (decode_stream.c:139)
==31827==    by 0x50C075C: reached_eof (decode_stream.c:158)
==31827==    by 0x50C086E: MVM_string_decodestream_get_all (decode_stream.c:494)
==31827==    by 0x508B531: MVM_decoder_take_all_chars (Decoder.c:263)
==31827==    by 0x5022294: MVM_interp_run (interp.c:5031)
==31827==    by 0x50FE6D5: MVM_vm_run_file (moar.c:412)
==31827==    by 0x109731: main (main.c:299)
==31827==  Address 0xbb41c80 is 0 bytes after a block of size 512 alloc'd
==31827==    at 0x4C2CEDF: malloc (vg_replace_malloc.c:299)
==31827==    by 0x50C5E23: MVM_malloc (alloc.h:2)
==31827==    by 0x50C5E23: MVM_string_utf8_c8_decodestream (utf8_c8.c:471)
==31827==    by 0x50C04E7: run_decode (decode_stream.c:139)
==31827==    by 0x50C075C: reached_eof (decode_stream.c:158)
==31827==    by 0x50C086E: MVM_string_decodestream_get_all (decode_stream.c:494)
==31827==    by 0x508B531: MVM_decoder_take_all_chars (Decoder.c:263)
==31827==    by 0x5022294: MVM_interp_run (interp.c:5031)
==31827==    by 0x50FE6D5: MVM_vm_run_file (moar.c:412)
==31827==    by 0x109731: main (main.c:299)
==31827== 
==31827== Invalid read of size 2
==31827==    at 0x4C314AF: memcpy@GLIBC_2.2.5 (vg_replace_strmem.c:1021)
==31827==    by 0x50C0EC3: get_all_in_buffer (decode_stream.c:477)
==31827==    by 0x508B531: MVM_decoder_take_all_chars (Decoder.c:263)
==31827==    by 0x5022294: MVM_interp_run (interp.c:5031)
==31827==    by 0x50FE6D5: MVM_vm_run_file (moar.c:412)
==31827==    by 0x109731: main (main.c:299)
==31827==  Address 0xbb41c80 is 0 bytes after a block of size 512 alloc'd
==31827==    at 0x4C2CEDF: malloc (vg_replace_malloc.c:299)
==31827==    by 0x50C5E23: MVM_malloc (alloc.h:2)
==31827==    by 0x50C5E23: MVM_string_utf8_c8_decodestream (utf8_c8.c:471)
==31827==    by 0x50C04E7: run_decode (decode_stream.c:139)
==31827==    by 0x50C075C: reached_eof (decode_stream.c:158)
==31827==    by 0x50C086E: MVM_string_decodestream_get_all (decode_stream.c:494)
==31827==    by 0x508B531: MVM_decoder_take_all_chars (Decoder.c:263)
==31827==    by 0x5022294: MVM_interp_run (interp.c:5031)
==31827==    by 0x50FE6D5: MVM_vm_run_file (moar.c:412)
==31827==    by 0x109731: main (main.c:299)
==31827== 
==31827== Invalid read of size 2
==31827==    at 0x4C314A0: memcpy@GLIBC_2.2.5 (vg_replace_strmem.c:1021)
==31827==    by 0x50C0EC3: get_all_in_buffer (decode_stream.c:477)
==31827==    by 0x508B531: MVM_decoder_take_all_chars (Decoder.c:263)
==31827==    by 0x5022294: MVM_interp_run (interp.c:5031)
==31827==    by 0x50FE6D5: MVM_vm_run_file (moar.c:412)
==31827==    by 0x109731: main (main.c:299)
==31827==  Address 0xbb41c82 is 2 bytes after a block of size 512 alloc'd
==31827==    at 0x4C2CEDF: malloc (vg_replace_malloc.c:299)
==31827==    by 0x50C5E23: MVM_malloc (alloc.h:2)
==31827==    by 0x50C5E23: MVM_string_utf8_c8_decodestream (utf8_c8.c:471)
==31827==    by 0x50C04E7: run_decode (decode_stream.c:139)
==31827==    by 0x50C075C: reached_eof (decode_stream.c:158)
==31827==    by 0x50C086E: MVM_string_decodestream_get_all (decode_stream.c:494)
==31827==    by 0x508B531: MVM_decoder_take_all_chars (Decoder.c:263)
==31827==    by 0x5022294: MVM_interp_run (interp.c:5031)
==31827==    by 0x50FE6D5: MVM_vm_run_file (moar.c:412)
==31827==    by 0x109731: main (main.c:299)
==31827== 
896
==31827== 
==31827== HEAP SUMMARY:
==31827==     in use at exit: 61,754,631 bytes in 197,770 blocks
==31827==   total heap usage: 276,753 allocs, 78,983 frees, 149,393,876 bytes allocated
==31827== 
==31827== LEAK SUMMARY:
==31827==    definitely lost: 544 bytes in 6 blocks
==31827==    indirectly lost: 0 bytes in 0 blocks
==31827==      possibly lost: 235,776 bytes in 4,194 blocks
==31827==    still reachable: 61,518,311 bytes in 193,570 blocks
==31827==         suppressed: 0 bytes in 0 blocks
==31827== Rerun with --leak-check=full to see details of leaked memory
==31827== 
==31827== For counts of detected and suppressed errors, rerun with: -v
==31827== ERROR SUMMARY: 3 errors from 3 contexts (suppressed: 0 from 0)
```

**Comment by xelak6** [comment]
When reading, slurp() uses $!decoder.add_bytes() and $!decoder.consume-all-chars() at the end.
When reading from file, all the bytes are usually read at once, but when reading from a pipe, the data comes in smaller packets and so slurp() calls $!decoder.add_bytes() several times which causes then the failure (at least in combination with 'utf8-c8').

Here the ouput from my example script (only the last line is correct, since all data are read at once):

https://gist.github.com/xelak6/c9812201a1902f07fb4d812b15084892

add-bytes-at-once:    100, output-chars: 10700, decoder-bytes-available: -60
add-bytes-at-once:   1000, output-chars: 10991, decoder-bytes-available: -360
add-bytes-at-once:  10000, output-chars: 19919, decoder-bytes-available: -9360
add-bytes-at-once: 100000, output-chars: 10640, decoder-bytes-available: 0

**Comment by zoffixznet** [comment]
After version bumps, [the new test](https://github.com/perl6/roast/pull/461) now passes, and I get all the content now, but I also get an occasional segfault, about 10% of the time.

It doesn't seem to occur when using working variants listed in OP.

```
cpan@perlbuild4~/R/rakudo (master)$ ./perl6 -e 'run("curl", :enc<utf8-c8>, :out, "-s", "https://www.google.com").out.slurp.chars.say'
10812
cpan@perlbuild4~/R/rakudo (master)$ ./perl6 -e 'run("curl", :enc<utf8-c8>, :out, "-s", "https://www.google.com").out.slurp.chars.say'
Segmentation fault
cpan@perlbuild4~/R/rakudo (master)$ ./perl6 -e 'run("curl", :enc<utf8-c8>, :out, "-s", "https://www.google.com").out.slurp.chars.say'
10801
cpan@perlbuild4~/R/rakudo (master)$ ./perl6 -e 'run("curl", :enc<utf8-c8>, :out, "-s", "https://www.google.com").out.slurp.chars.say'
10739
cpan@perlbuild4~/R/rakudo (master)$ ./perl6 -e 'run("curl", :enc<utf8-c8>, :out, "-s", "https://www.google.com").out.slurp.chars.say'
10775
cpan@perlbuild4~/R/rakudo (master)$ ./perl6 -e 'run("curl", :enc<utf8-c8>, :out, "-s", "https://www.google.com").out.slurp.chars.say'
10795
cpan@perlbuild4~/R/rakudo (master)$ ./perl6 -e 'run("curl", :enc<utf8-c8>, :out, "-s", "https://www.google.com").out.slurp.chars.say'
10751
cpan@perlbuild4~/R/rakudo (master)$ ./perl6 -e 'run("curl", :enc<utf8-c8>, :out, "-s", "https://www.google.com").out.slurp.chars.say'
10748
cpan@perlbuild4~/R/rakudo (master)$ ./perl6 -e 'run("curl", :enc<utf8-c8>, :out, "-s", "https://www.google.com").out.slurp.chars.say'
10773
cpan@perlbuild4~/R/rakudo (master)$ ./perl6 -e 'run("curl", :enc<utf8-c8>, :out, "-s", "https://www.google.com").out.slurp.chars.say'
10787
cpan@perlbuild4~/R/rakudo (master)$ ./perl6 -e 'run("curl", :enc<utf8-c8>, :out, "-s", "https://www.google.com").out.slurp.chars.say'
10784
cpan@perlbuild4~/R/rakudo (master)$ ./perl6 -e 'run("curl", :enc<utf8-c8>, :out, "-s", "https://www.google.com").out.slurp.chars.say'
Segmentation fault
cpan@perlbuild4~/R/rakudo (master)$ ./perl6 -e 'run("curl", :enc<utf8-c8>, :out, "-s", "https://www.google.com").out.slurp.chars.say'
10800
```

**Comment by zoffixznet** [comment]
FWIW, even when I ramp up the number of iterations in the new test, no SEGV occurs, so we'll need to devise another test to cover the SEGV

**Comment by zoffixznet** [comment]
http://colabti.org/irclogger/irclogger_log/perl6-dev?date=2018-08-07#l760

```
23:03 | MasterDuke | #6 get_all_in_buffer (tc=tc@entry=0x555555559c80, ds=0x55555818dcf0) at src/strings/decode_stream.c:481
23:04 | MasterDuke | #7 0x00007ffff7a6d28a in MVM_string_decodestream_get_all (tc=tc@entry=0x555555559c80, ds=<optimized out>) at src/strings/decode_stream.c:495
23:04 | MasterDuke | from ` perl6-gdb-m 'run("curl", :enc<utf8-c8>, :out, "-s", "https://www.google.com").out.slurp.chars.say'`
23:03 | MasterDuke | #6 get_all_in_buffer (tc=tc@entry=0x555555559c80, ds=0x55555818dcf0) at src/strings/decode_stream.c:481
23:04 | MasterDuke | #7 0x00007ffff7a6d28a in MVM_string_decodestream_get_all (tc=tc@entry=0x555555559c80, ds=<optimized out>) at src/strings/decode_stream.c:495
23:04 | MasterDuke | from ` perl6-gdb-m 'run("curl", :enc<utf8-c8>, :out, "-s", "https://www.google.com").out.slurp.chars.say'`
```

**Comment by zoffixznet** [comment]
```
2018.06 zoffix@VirtualBox~/R/rakudo (master)$ ./perl6-valgrind-m -e 'run("curl", :enc<utf8-c8>, :out, "-s", "https://www.google.com").out.slurp.chars.say'
================================================================================================
This is Rakudo Perl 6 running in valgrind, a tool for debugging and profiling programs.
Running a program in valgrind usually takes *a lot* more time than running it directly,
so please be patient.
Valgrind options can be added with MVM_VALGRIND_OPTS environment variable.
This Rakudo version is 2018.06.352.g.677.f.23.fb.3 built on MoarVM version 2018.06.385.g.3.e.679.da.29,
running on ubuntu (14.04.5.LTS.Trusty.Tahr) / linux (4.2.0.30.generic)
------------------------------------------------------------------------------------------------
==7473== Memcheck, a memory error detector
==7473== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==7473== Using Valgrind-3.10.1 and LibVEX; rerun with -h for copyright info
==7473== Command: /home/zoffix/R/install/bin/moar --execname=./perl6-valgrind-m --libpath=. --libpath=blib --libpath=/home/zoffix/R/install/share/nqp/lib --libpath=/home/zoffix/R/install/share/nqp/lib /home/zoffix/R/rakudo/perl6.moarvm --nqp-lib=blib -e run("curl",\ :enc\<utf8-c8\>,\ :out,\ "-s",\ "https://www.google.com").out.slurp.chars.say
==7473== 
==7473== Invalid write of size 4
==7473==    at 0x5125A56: append_grapheme (utf8_c8.c:209)
==7473==    by 0x5125E03: process_bad_bytes (utf8_c8.c:298)
==7473==    by 0x512695E: MVM_string_utf8_c8_decodestream (utf8_c8.c:559)
==7473==    by 0x511F312: run_decode (decode_stream.c:139)
==7473==    by 0x511F39C: reached_eof (decode_stream.c:158)
==7473==    by 0x5120064: MVM_string_decodestream_get_all (decode_stream.c:494)
==7473==    by 0x50D3505: MVM_decoder_take_all_chars (Decoder.c:263)
==7473==    by 0x5032D01: MVM_interp_run (interp.c:5027)
==7473==    by 0x517B5ED: MVM_vm_run_file (moar.c:412)
==7473==    by 0x40164F: main (main.c:299)
==7473==  Address 0xf30ff9c is 0 bytes after a block of size 12,764 alloc'd
==7473==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==7473==    by 0x5124E95: MVM_malloc (alloc.h:2)
==7473==    by 0x5126595: MVM_string_utf8_c8_decodestream (utf8_c8.c:471)
==7473==    by 0x511F312: run_decode (decode_stream.c:139)
==7473==    by 0x511F39C: reached_eof (decode_stream.c:158)
==7473==    by 0x5120064: MVM_string_decodestream_get_all (decode_stream.c:494)
==7473==    by 0x50D3505: MVM_decoder_take_all_chars (Decoder.c:263)
==7473==    by 0x5032D01: MVM_interp_run (interp.c:5027)
==7473==    by 0x517B5ED: MVM_vm_run_file (moar.c:412)
==7473==    by 0x40164F: main (main.c:299)
==7473== 
==7473== Invalid read of size 2
==7473==    at 0x4C2F7EF: memcpy@@GLIBC_2.14 (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==7473==    by 0x511FFDC: get_all_in_buffer (decode_stream.c:477)
==7473==    by 0x5120077: MVM_string_decodestream_get_all (decode_stream.c:495)
==7473==    by 0x50D3505: MVM_decoder_take_all_chars (Decoder.c:263)
==7473==    by 0x5032D01: MVM_interp_run (interp.c:5027)
==7473==    by 0x517B5ED: MVM_vm_run_file (moar.c:412)
==7473==    by 0x40164F: main (main.c:299)
==7473==  Address 0xf30ff9c is 0 bytes after a block of size 12,764 alloc'd
==7473==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==7473==    by 0x5124E95: MVM_malloc (alloc.h:2)
==7473==    by 0x5126595: MVM_string_utf8_c8_decodestream (utf8_c8.c:471)
==7473==    by 0x511F312: run_decode (decode_stream.c:139)
==7473==    by 0x511F39C: reached_eof (decode_stream.c:158)
==7473==    by 0x5120064: MVM_string_decodestream_get_all (decode_stream.c:494)
==7473==    by 0x50D3505: MVM_decoder_take_all_chars (Decoder.c:263)
==7473==    by 0x5032D01: MVM_interp_run (interp.c:5027)
==7473==    by 0x517B5ED: MVM_vm_run_file (moar.c:412)
==7473==    by 0x40164F: main (main.c:299)
==7473== 
11255
==7473== 
==7473== HEAP SUMMARY:
==7473==     in use at exit: 61,983,564 bytes in 198,365 blocks
==7473==   total heap usage: 288,292 allocs, 89,927 frees, 149,531,236 bytes allocated
==7473== 
==7473== LEAK SUMMARY:
==7473==    definitely lost: 1,280 bytes in 10 blocks
==7473==    indirectly lost: 0 bytes in 0 blocks
==7473==      possibly lost: 235,264 bytes in 4,194 blocks
==7473==    still reachable: 61,747,020 bytes in 194,161 blocks
==7473==         suppressed: 0 bytes in 0 blocks
==7473== Rerun with --leak-check=full to see details of leaked memory
==7473== 
==7473== For counts of detected and suppressed errors, rerun with: -v
==7473== ERROR SUMMARY: 3 errors from 2 contexts (suppressed: 0 from 0)
2018.06 zoffix@VirtualBox~/R/rakudo (master)$ 
```

**Comment by zoffixznet** [comment]
Fixed in https://github.com/MoarVM/MoarVM/pull/936
