### ISSUE TITLE
Perl6 segfaults on launch

### ISSUE THREAD

**Issue by Kaiepi** [rakudo/rakudo#2252]
## The Problem
See title.

## Expected Behavior
The REPL should appear.

## Actual Behavior
MoarVM segfaults. Here's what the coredump shows:

```
bastille% perl6-gdb-m     
Segmentation fault (core dumped) 
c(gdb) core moar.core
Core was generated by `moar'.
Program terminated with signal 11, Segmentation fault.
Reading symbols from /usr/lib/libpthread.so.25.1...done.
Loaded symbols for /usr/lib/libpthread.so.25.1
Loaded symbols for /home/morfent/.perl6/bin/moar
Reading symbols from /home/morfent/.perl6/lib/libmoar.so...done.
Loaded symbols for //home/morfent/.perl6/lib/libmoar.so
Reading symbols from /usr/lib/libc.so.92.3...done.
Loaded symbols for /usr/lib/libc.so.92.3
Reading symbols from /usr/lib/libm.so.10.1...done.
Loaded symbols for /usr/lib/libm.so.10.1
Symbols already loaded for /usr/lib/libpthread.so.25.1
Reading symbols from /usr/lib/libkvm.so.17.0...done.
Loaded symbols for /usr/lib/libkvm.so.17.0
Reading symbols from /usr/libexec/ld.so...done.
Loaded symbols for /usr/libexec/ld.so
Reading symbols from /home/morfent/.perl6/share/perl6/runtime/dynext/libperl6_ops_moar.so...done.
Loaded symbols for /home/morfent/.perl6/share/perl6/runtime/dynext/libperl6_ops_moar.so
Reading symbols from /usr/local/lib/libuv.so.1.0...done.
Loaded symbols for /usr/local/lib/libuv.so.1.0
#0  0x00000297d35e7620 in MVM_string_ascii_decode (tc=0x297818dc400, result_type=0x2981e203160, ascii=0x2980faa77c9 "rakudo_scalar", 
    bytes=13) at src/strings/ascii.c:6
6	    MVMString *result = (MVMString *)REPR(result_type)->allocate(tc, STABLE(result_type));
(gdb) bt
#0  0x00000297d35e7620 in MVM_string_ascii_decode (tc=0x297818dc400, result_type=0x2981e203160, ascii=0x2980faa77c9 "rakudo_scalar", 
    bytes=13) at src/strings/ascii.c:6
#1  0x00000297d35e779e in MVM_string_ascii_decode_nt (tc=0x297818dc400, result_type=0x2981e203160, 
    ascii=0x2980faa77c9 "rakudo_scalar") at src/strings/ascii.c:34
#2  0x000002980f9a5cf3 in Rakudo_containers_setup () from /home/morfent/.perl6/share/perl6/runtime/dynext/libperl6_ops_moar.so
#3  0x000002980f9a3b79 in p6init () from /home/morfent/.perl6/share/perl6/runtime/dynext/libperl6_ops_moar.so
#4  0x00000297d34fa792 in MVM_interp_run (tc=0x297818dc400, initial_invoke=0x297d36430ac <toplevel_initial_invoke>, 
    invoke_data=0x297facbe7c0) at src/core/interp.c:6005
#5  0x00000297d364320e in MVM_vm_run_file (instance=0x2981e6bf000, 
    filename=0x7f7fffffa775 "/home/morfent/.perl6/share/perl6/runtime/perl6.moarvm") at src/moar.c:420
#6  0x0000029533500ed5 in main (argc=8, argv=0x7f7fffffa4e8) at src/main.c:299
```

I tried to debug it, but my system deadlocks at some point in code dealing with the JIT compiler while running `MVM_6model_add_container_config`. Trying to deref `result_type` in `MVM_string_ascii_decode` is what causes the segfault at the very end.

## Steps to Reproduce

Run perl6.

## Environment
* Operating system: 
OpenBSD bastille.kennel.qt 6.3 GENERIC.MP#4 amd64
* Compiler version (`perl6 -v`): 
Can't run `perl6 -v` since it segfaults, but here's what `git describe` shows for what I have installed:
  - MoarVM: 2018.08-27-ge17a53b87
  - Rakudo: 2018.08-41-ge436f4e53

**Comment by Kaiepi** [comment]
I should add MVM_SPESH_DISABLE and MVM_JIT_DISABLE do not mitigate this
