### ISSUE TITLE
Crashes in t/spec/S17-promise/lock-async-stress2.t

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2261]
(note, this is a stresstest and so it doesn't get run with `make spectest`)

I get a rare failure in t/spec/S17-promise/lock-async-stress2.t test

First, I spotted it in a stresstest run:

```
Test Summary Report
-------------------
t/spec/S17-promise/lock-async-stress2.t                         (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 1 tests but ran 0.
Files=1305, Tests=153122, 147 wallclock secs (21.29 usr  3.40 sys + 3158.53 cusr 155.61 csys = 3338.83 CPU)
Result: FAIL
Makefile:586: recipe for target 'm-stresstest5' failed
make: *** [m-stresstest5] Error 1
```

I then ran just that test file and it failed again right away with this message about dispatch cache:
```
cpan@perlbuild4~/R/rakudo (master)$ z t t/spec/S17-promise/lock-async-stress2.t
t/spec/S17-promise/lock-async-stress2.t .. 
1..1
MoarVM panic: Corrupt multi dispatch cache: cur_node != 0, re-check == (nil)
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests 
Test Summary Report
-------------------
t/spec/S17-promise/lock-async-stress2.t (Wstat: 256 Tests: 0 Failed: 0)
  Non-zero exit status: 1
  Parse errors: Bad plan.  You planned 1 tests but ran 0.
Files=1, Tests=0,  2 wallclock secs ( 0.02 usr  0.00 sys +  2.88 cusr  0.22 csys =  3.12 CPU)
Result: FAIL
The spawned command 't/fudgeandrun' exited unsuccessfully (exit code: 1)
  in block <unit> at /home/cpan/zscript/bin/z line 154
```

I then ran 20 more runs, all succeeded. I then fired off make stresstest in another terminal to put the system under load (it's my 24-core VM), 

I did 11 more runs, all of which still succeeded, but the 12th run finally crashed, now with a different error:

```
$ z t t/spec/S17-promise/lock-async-stress2.t
t/spec/S17-promise/lock-async-stress2.t .. 
1..1
An operation first awaited:
  in block <unit> at t/spec/S17-promise/lock-async-stress2.t line 10

Died with the exception:
    Not enough positional arguments; needed at least 2
      in block  at t/spec/S17-promise/lock-async-stress2.t line 11

# Looks like you planned 1 test, but ran 0
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 1/1 subtests 
```

**Comment by aeruder** [comment]
I believe I am seeing this in a real-life program too very very occasionally, here's a full backtrace from that with `--ll-exception`.

```
% perl6 --version
This is Rakudo version 2018.09-72-g687a3cbb0 built on MoarVM version 2018.09-123-g0191bd9cf
implementing Perl 6.c.
```

```
Unhandled exception in code scheduled on thread 21
Not enough positional arguments; needed at least 2
  in sub cas at SETTING::src/core/atomicops.pm6 line 22
  in block  at SETTING::src/core/Lock/Async.pm6 line 76
  in method lock at SETTING::src/core/Lock/Async.pm6 line 64
  in method protect-or-queue-on-recursion at SETTING::src/core/Lock/Async.pm6 line 137
  in method run-supply-code at SETTING::src/core/Supply.pm6 line 1986
  in block  at SETTING::src/core/Supply.pm6 line 1929
  in block  at SETTING::src/core/Supply.pm6 line 1884
  in method run-emit at SETTING::src/core/Supply.pm6 line 1883
  in any  at /Users/aeruder/.rakudo/share/perl6/runtime/CORE.setting.moarvm line 1
  in block  at SETTING::src/core/Supply.pm6 line 1008
  in block  at SETTING::src/core/Supply.pm6 line 1988
  in method run-under-recursion-list at SETTING::src/core/Lock/Async.pm6 line 198
  in method run-with-updated-recursion-list at SETTING::src/core/Lock/Async.pm6 line 178
  in method protect-or-queue-on-recursion at SETTING::src/core/Lock/Async.pm6 line 141
  in method run-supply-code at SETTING::src/core/Supply.pm6 line 1986
  in block  at SETTING::src/core/Supply.pm6 line 1929
  in block  at SETTING::src/core/Supply.pm6 line 1884
  in method run-emit at SETTING::src/core/Supply.pm6 line 1883
  in any  at /Users/aeruder/.rakudo/share/perl6/runtime/CORE.setting.moarvm line 1
  in block  at SETTING::src/core/Encoding/Decoder/Builtin.pm6 line 71
  in block  at SETTING::src/core/Supply.pm6 line 1988
  in method run-under-recursion-list at SETTING::src/core/Lock/Async.pm6 line 198
  in method run-with-updated-recursion-list at SETTING::src/core/Lock/Async.pm6 line 178
  in method protect-or-queue-on-recursion at SETTING::src/core/Lock/Async.pm6 line 141
  in method run-supply-code at SETTING::src/core/Supply.pm6 line 1986
  in block  at SETTING::src/core/Supply.pm6 line 1929
  in block  at SETTING::src/core/Supply.pm6 line 255
  in block  at SETTING::src/core/Supply.pm6 line 220
  in method run-under-recursion-list at SETTING::src/core/Lock/Async.pm6 line 198
  in method run-with-updated-recursion-list at SETTING::src/core/Lock/Async.pm6 line 178
  in method protect-or-queue-on-recursion at SETTING::src/core/Lock/Async.pm6 line 137
  in block  at SETTING::src/core/Supply.pm6 line 219
  in block  at SETTING::src/core/Supply.pm6 line 1690
  in block  at SETTING::src/core/Supply.pm6 line 1690
  in method emit at SETTING::src/core/Supply.pm6 line 1686
  in block  at SETTING::src/core/Proc/Async.pm6 line 265
  in method emit-events at SETTING::src/core/Rakudo/Internals.pm6 line 605
  in block  at SETTING::src/core/Rakudo/Internals.pm6 line 589
  in block  at SETTING::src/core/Rakudo/Internals.pm6 line 584
  in method protect at SETTING::src/core/Lock/Async.pm6 line 124
  in method process at SETTING::src/core/Rakudo/Internals.pm6 line 583
  in block  at SETTING::src/core/Proc/Async.pm6 line 270
  in block  at SETTING::src/core/ThreadPoolScheduler.pm6 line 243
  in block  at SETTING::src/core/ThreadPoolScheduler.pm6 line 243
  in method run-one at SETTING::src/core/ThreadPoolScheduler.pm6 line 236
  in block  at SETTING::src/core/ThreadPoolScheduler.pm6 line 307
```

**Comment by dogbert17** [comment]
Still present in 

    This is Rakudo version 2019.07.1-452-g7cf73de built on MoarVM version 2019.07.1-311-g8caf9fd
    implementing Perl 6.d.

    ...
    Thread 3 "moar" hit Breakpoint 1, MVM_panic (exitCode=1, messageFormat=0x7ffff763bd80 "Corrupt multi dispatch cache: cur_node != 0, re-check == %p") at src/core/exceptions.c:832
    832	MVM_NO_RETURN void MVM_panic(MVMint32 exitCode, const char *messageFormat, ...) {
    (gdb) bt
    #0  MVM_panic (exitCode=1, messageFormat=0x7ffff763bd80 "Corrupt multi dispatch cache: cur_node != 0, re-check == %p") at src/core/exceptions.c:832
    #1  0x00007ffff74f605a in MVM_multi_cache_add (tc=0x33dd4e0, cache_obj=0x7fffe4069a40, capture=0x7ffff1088708, result=0x2857820) at src/6model/reprs/MVMMultiCache.c:258
    #2  0x00007ffff7440141 in MVM_interp_run (tc=0x33dd4e0, initial_invoke=0x7ffff7479b9f <thread_initial_invoke>, invoke_data=0x33ff980) at src/core/interp.c:1510
    #3  0x00007ffff7479ce8 in start_thread (data=0x33ff980) at src/core/threads.c:87
    #4  0x00007ffff69606ba in start_thread (arg=0x7ffff391c700) at pthread_create.c:333
    #5  0x00007ffff6f8641d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
    (gdb) f 1
    #1  0x00007ffff74f605a in MVM_multi_cache_add (tc=0x33dd4e0, cache_obj=0x7fffe4069a40, capture=0x7ffff1088708, result=0x2857820) at src/6model/reprs/MVMMultiCache.c:258
    258	            MVM_panic(1, "Corrupt multi dispatch cache: cur_node != 0, re-check == %p",
    (gdb) l
    253	        }
    254	
    255	        /* If we found a candidate, something inconsistent, as we
    256	         * checked for non-entry above. */
    257	        if (cur_node != 0)
    258	            MVM_panic(1, "Corrupt multi dispatch cache: cur_node != 0, re-check == %p",
    259	                MVM_multi_cache_find(tc, cache_obj, capture));
    260	    }
    261	
    262	    /* Now calculate the new size we'll need to allocate. */
    (gdb) c
    Continuing.
    MoarVM panic: Corrupt multi dispatch cache: cur_node != 0, re-check == (nil)

**Comment by lizmat** [comment]
May fixes were done improving stability since then, so closing
