### ISSUE TITLE
js backend REPL broken

### ISSUE THREAD

**Issue by coke** [rakudo/rakudo#2359]
## The Problem

While this runs and generates the correct output:

```
./perl6-js -e 'say 3'
3
```

Trying to get to the REPL fails:

```
$ ./perl6-js
===SORRY!===
<<wrapped exception:
TypeError: Cannot read property 'staticCode' of undefined
    at Object.op.ctxouterskipthunks (/Users/coke/sandbox/rakudo/nqp/src/vm/js/nqp-runtime/core.js:1604:34)
    at CodeRef.cuid6411 [as $$call] (/Users/coke/sandbox/rakudo/node_modules/CORE.setting.js:511101:28)
    at ObjConstructor.$$call (/Users/coke/sandbox/rakudo/nqp/src/vm/js/nqp-runtime/sixmodel.js:200:29)
    at CodeRef.cuid6430 (/Users/coke/sandbox/rakudo/node_modules/CORE.setting.js:512449:138)
    at CodeRef.$$apply (/Users/coke/sandbox/rakudo/nqp/src/vm/js/nqp-runtime/code-ref.js:95:24)
    at ObjConstructor.$$apply (/Users/coke/sandbox/rakudo/nqp/src/vm/js/nqp-runtime/sixmodel.js:203:31)
    at CodeRef.cuid740 [as $$call] (/Users/coke/sandbox/rakudo/node_modules/CORE.setting.js:81741:40)
    at ObjConstructor.$$call (/Users/coke/sandbox/rakudo/nqp/src/vm/js/nqp-runtime/sixmodel.js:200:29)
```

## Environment
* Operating system: mac osx 10.13.6
* Compiler version (`perl6 -v`):

```
$ ./perl6-js --version
This is Rakudo version 2018.09-381-g605bcb391 built on JS
implementing Perl 6.c.
$ node --version
v10.11.0
```

**Comment by pmurias** [comment]
Fixed by b781479ea583d892135ae30182efbbdb560f08e2.
