### ISSUE TITLE
Trace traps and double frees when building Rakudo

### ISSUE THREAD

**Issue by Kaiepi** [rakudo/rakudo#2520]
## The Problem
There are two different issues here:
- moar core dumps due to a trace trap at some point when building nqp unless `MVM_JIT_DISABLE` or `MVM_SPESH_DISABLE` is enabled
- moar core dumps again due to a double free when running `install-core-dist.p6`

## Expected Behavior
The build should succeed.

## Actual Behavior
It doesn't.

## Steps to Reproduce

For the first issue, run:
`$ ./Configure.pl --gen-moar --gen-nqp --moar-option=--optimize=0 --moar-option=--debug=3`

For the second, run:
`$ MVM_JIT_DISABLE=1 ./Configure.pl --gen-moar --gen-nqp --moar-option=--optimize=0 --moar-option=--debug=3`

## Environment
* Operating system: 
OpenBSD bastille.kennel.qt 6.4 GENERIC.MP#364 amd64
* Compiler version (`perl6 -v`): 
This is Rakudo version 2018.11-9-g9f5cc8d1b built on MoarVM version 2018.11-10-gfdc73f300

**Comment by AlexDaniel** [comment]
So that only happens on openbsd? Am I understanding it correctly?

**Comment by Kaiepi** [comment]
This doesn't happen on FreeBSD, so it looks like that may be the case. Here's the backtrace from the core dump:
```
bastille% perl6-gdb-m
Trace/BPT trap (core dumped) 
(gdb) core moar.core
Core was generated by `moar'.
Program terminated with signal 5, Trace/breakpoint trap.
Reading symbols from /usr/lib/libpthread.so.25.1...done.
Loaded symbols for /usr/lib/libpthread.so.25.1
Loaded symbols for /home/morfent/.perl6/bin/moar
Reading symbols from /home/morfent/.perl6/lib/libmoar.so...done.
Loaded symbols for //home/morfent/.perl6/lib/libmoar.so
Reading symbols from /usr/lib/libc.so.92.5...done.
Loaded symbols for /usr/lib/libc.so.92.5
Reading symbols from /usr/lib/libm.so.10.1...done.
Loaded symbols for /usr/lib/libm.so.10.1
Symbols already loaded for /usr/lib/libpthread.so.25.1
Reading symbols from /usr/lib/libkvm.so.17.0...done.
Loaded symbols for /usr/lib/libkvm.so.17.0
Reading symbols from /usr/libexec/ld.so...done.
Loaded symbols for /usr/libexec/ld.so
Reading symbols from /home/morfent/.perl6/share/perl6/runtime/dynext/libperl6_ops_moar.so...done.
Loaded symbols for /home/morfent/.perl6/share/perl6/runtime/dynext/libperl6_ops_moar.so
#0  0x00000d90867cbe63 in MVM_frame_try_return (tc=0x7f7ffffbd270) at src/core/frame.c:1005
1005	}
Current language:  auto; currently minimal
(gdb) bt full
#0  0x00000d90867cbe63 in MVM_frame_try_return (tc=0x7f7ffffbd270) at src/core/frame.c:1005
	cur_frame = (MVMFrame *) 0x33
#1  0x00000d9086987b88 in MVM_jit_code_enter (tc=0xd907d46e400, code=0xd90725c0300, cu=0xd9058f735d0) at src/jit/interface.c:24
	label = (void *) 0xd9054a7c036
#2  0x00000d90867bffa8 in MVM_interp_run (tc=0xd907d46e400, initial_invoke=0xd908695dbc0 <toplevel_initial_invoke>, invoke_data=0xd90925db658) at src/core/interp.c:6066
	jc = (MVMJitCode *) 0xd90725c0300
	op = 887
	LABELS = 0xd90870b3530
	cur_op = (MVMuint8 *) 0xd906dae03b8 <Address 0xd906dae03b8 out of bounds>
	bytecode_start = (MVMuint8 *) 0xd906dadfd38 <Address 0xd906dadfd38 out of bounds>
	reg_base = (MVMRegister *) 0xd90956ac448
	cu = (MVMCompUnit *) 0xd9058f73f80
	cur_callsite = (MVMCallsite *) 0xd90870fc048
#3  0x00000d908695dae5 in MVM_vm_run_file (instance=0xd90944f4000, filename=0x7f7ffffbd6e5 "/home/morfent/.perl6/share/perl6/runtime/perl6.moarvm") at src/moar.c:440
	tc = (MVMThreadContext *) 0xd907d46e400
	cu = (MVMCompUnit *) 0xd9058f73000
#4  0x00000d8daec00db3 in main (argc=8, argv=0x7f7ffffbd458) at src/main.c:301
	instance = (MVMInstance *) 0xd90944f4000
	input_file = 0x7f7ffffbd6e5 "/home/morfent/.perl6/share/perl6/runtime/perl6.moarvm"
	executable_name = 0x7f7ffffbd631 "/home/morfent/.perl6/bin/perl6-gdb-m"
	lib_path = 0x7f7ffffbd3c0
	dump = 0
	full_cleanup = 0
	argi = 6
	lib_path_i = 3
	flag = -2
	interval_id = 0
	telemeh_inited = 0 '\0'
	debugserverport = 0
	start_suspended = 0
```

**Comment by AlexDaniel** [comment]
Am I understanding it right that this issue didn't exist previously?

**Comment by Kaiepi** [comment]
It didn't previously, no

**Comment by AlexDaniel** [comment]
@Kaiepi OK, can you bisect it then?

**Comment by Kaiepi** [comment]
This no longer happens but I can check
