### ISSUE TITLE
Building NPQ with MoarVM fails with Trace/BPT trap (core dumped) 

### ISSUE THREAD

**Issue by Kaiepi** [rakudo/rakudo#2658]
## The Problem
See title.

## Expected Behavior
NQP should build.

## Actual Behavior
It fails:
```
bastille% make
perl -MExtUtils::Command -e mkpath gen/moar/stage1/gen
perl tools/build/gen-cat.pl moar src/how/Archetypes.nqp  src/how/RoleToRoleApplier.nqp  src/how/NQPConcreteRoleHOW.nqp  src/how/RoleToClassApplier.nqp  src/how/NQPCurriedRoleHOW.nqp  src/how/NQPParametricRoleHOW.nqp  src/how/NQPClassHOW.nqp  src/how/NQPNativeHOW.nqp  src/how/NQPAttribute.nqp  src/how/NQPModuleHOW.nqp  src/how/EXPORTHOW.nqp   > gen/moar/stage1/nqpmo.nqp
/home/morfent/.perl6/bin/moar --libpath=src/vm/moar/stage0 src/vm/moar/stage0/nqp.moarvm --bootstrap --setting=NULL --no-regex-lib --target=mbc --stable-sc=stage1  --output=gen/moar/stage1/nqpmo.moarvm gen/moar/stage1/nqpmo.nqp
Trace/BPT trap (core dumped) 
*** Error 133 in /home/morfent/Documents/perl6/nqp (Makefile:257 'gen/moar/stage1/nqpmo.moarvm')
```

## Steps to Reproduce

Run `./Configure.pl --gen-moar --gen-nqp --backends=moar`

## Environment
* Operating system: 
OpenBSD bastille.kennel.qt 6.4 GENERIC.MP#364 amd64
* Compiler version (`perl6 -v`): 
This is Rakudo version 2018.12 built on MoarVM version 2018.12
implementing Perl 6.d.

**Comment by Kaiepi** [comment]
`MVM_JIT_DISABLE=1` mitigates this

**Comment by Kaiepi** [comment]
Here's the backtrace for those interested:
```
(gdb) bt
#0  0x000006b608e6579b in MVM_frame_try_return () from //home/morfent/.perl6/lib/libmoar.so
#1  0x000006b608f6977b in MVM_jit_code_enter () from //home/morfent/.perl6/lib/libmoar.so
#2  0x000006b608e5e75f in MVM_interp_run () from //home/morfent/.perl6/lib/libmoar.so
#3  0x000006b608f54823 in MVM_vm_run_file () from //home/morfent/.perl6/lib/libmoar.so
#4  0x000006b350000b62 in main () from /home/morfent/.perl6/bin/moar
```

**Comment by AlexDaniel** [comment]
I assume that's new?

**Comment by Kaiepi** [comment]
It is

**Comment by Kaiepi** [comment]
This doesn't happen anymore.
