### ISSUE TITLE
SEGV in t/04-nativecall/20-concurrent.t

### ISSUE THREAD

**Issue by MasterDuke17** [rakudo/rakudo#3030]
While running in a loop with a spectest also running in the background.
```
================================================================================================
This is Rakudo Perl 6 running in the  debugger, which often allows the user to generate useful back-
traces to debug or report issues in Rakudo, the MoarVM backend or the currently running code.

This Rakudo version is 2019.03.1.672.g.669.a.3.b.9.f.3 built on MoarVM version 2019.05.99.g.729303.de.7,
running on ubuntu (19.04.Disco.Dingo) / linux (21.Ubuntu.SMP.Mon.Jun.24.09.32.09.UTC.2019)

Type `bt full` to generate a backtrace if applicable, type `q` to quit or `help` for help.
------------------------------------------------------------------------------------------------
Reading symbols from /home/dan/Source/perl6/install/bin/moar...
Starting program: /home/dan/Source/perl6/install/bin/moar --execname=/home/dan/Source/perl6/rakudo/perl6-gdb-m --libpath=/home/dan/Source/perl6/rakudo --libpath=/home/dan/Source/perl6/rakudo/blib --libpath= --libpath=/home/dan/Source/perl6/install/share/nqp/lib /home/dan/Source/perl6/rakudo/perl6.moarvm --nqp-lib=/home/dan/Source/perl6/rakudo/blib --ll-exception t/04-nativecall/20-concurrent.t
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff6ff1700 (LWP 6526)]
1..3
[New Thread 0x7fffeffff700 (LWP 6571)]
[New Thread 0x7fffef7fe700 (LWP 6572)]
[New Thread 0x7fffeeffd700 (LWP 6573)]
[Detaching after fork from child process 6574]
[New Thread 0x7fffee7fc700 (LWP 6576)]
[Detaching after fork from child process 6583]
ok 1 - Correct results when running native code across threads

Thread 1 "moar" received signal SIGSEGV, Segmentation fault.
0x00007ffff79d5bfd in MVM_repr_clone (tc=0x55555555acc0, obj=0x100000000) at src/6model/reprconv.c:30
30          if (IS_CONCRETE(obj)) {
(gdb) bt
#0  0x00007ffff79d5bfd in MVM_repr_clone (tc=0x55555555acc0, obj=0x100000000) at src/6model/reprconv.c:30
#1  0x00007ffff5ba77b3 in ?? ()
#2  0x0000000000000008 in ?? ()
#3  0x00005555557ee760 in ?? ()
#4  0x000055555555acc0 in ?? ()
#5  0x00007ffff7eac5a0 in two_args_callsite () from //home/dan/Source/perl6/install/lib/libmoar.so
#6  0x00005555557ee760 in ?? ()
#7  0xef75222290e5bc00 in ?? ()
#8  0x00007fffffffd6d8 in ?? ()
#9  0x00007ffff7142a20 in ?? ()
#10 0x000055555555acc0 in ?? ()
#11 0x00007ffff7142890 in ?? ()
#12 0x00005555582d1958 in ?? ()
#13 0x0000000000000000 in ?? ()
(gdb) call MVM_dump_backtrace(tc)
   at SETTING::src/core/Mu.pm6:113  (/home/dan/Source/perl6/rakudo/CORE.setting.moarvm:new)
 from t/04-nativecall/20-concurrent.t:30  (<ephemeral file>:)
 from t/04-nativecall/20-concurrent.t:28  (<ephemeral file>:<unit>)
 from t/04-nativecall/20-concurrent.t:1  (<ephemeral file>:<unit-outer>)
 from gen/moar/stage2/NQPHLL.nqp:1835  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:eval)
 from gen/moar/stage2/NQPHLL.nqp:2039  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:evalfiles)
 from gen/moar/stage2/NQPHLL.nqp:1969  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:command_eval)
 from src/Perl6/Compiler.nqp:52  (/home/dan/Source/perl6/rakudo/blib/Perl6/Compiler.moarvm:command_eval)
 from gen/moar/stage2/NQPHLL.nqp:1924  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:command_line)
 from gen/moar/main.nqp:82  (/home/dan/Source/perl6/rakudo/perl6.moarvm:MAIN)
 from gen/moar/main.nqp:47  (/home/dan/Source/perl6/rakudo/perl6.moarvm:<mainline>)
 from <unknown>:1  (/home/dan/Source/perl6/rakudo/perl6.moarvm:<main>)
 from <unknown>:1  (/home/dan/Source/perl6/rakudo/perl6.moarvm:<entry>)
(gdb)
```

**Comment by MasterDuke17** [comment]
While running in a loop with a spectest also running in the background. MVM_GC_DEBUG=1, jit disabled, and gc nursery set to 8k.
```
Thread 1 "moar" hit Breakpoint 2, __GI_exit (status=status@entry=0) at exit.c:139
139     exit.c: No such file or directory.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff73be700 (LWP 30263)]
1..3
[New Thread 0x7ffff4836700 (LWP 30267)]
[New Thread 0x7fffeffff700 (LWP 30268)]
[New Thread 0x7fffef7fe700 (LWP 30269)]
[Detaching after fork from child process 30270]
[New Thread 0x7fffeeffd700 (LWP 30274)]
[Detaching after fork from child process 30275]
[New Thread 0x7fffee7fc700 (LWP 30279)]
ok 1 - Correct results when running native code across threads
[Switching to Thread 0x7ffff73be700 (LWP 30263)]

Thread 2 "moar" hit Breakpoint 1, MVM_panic (exitCode=exitCode@entry=1, messageFormat=messageFormat@entry=0x7ffff7adff68 "Must not GC when in the specializer/JIT\n") at src/core/exceptions.c:830
830     MVM_NO_RETURN void MVM_panic(MVMint32 exitCode, const char *messageFormat, ...) {
(gdb) bt
#0  MVM_panic (exitCode=exitCode@entry=1, messageFormat=messageFormat@entry=0x7ffff7adff68 "Must not GC when in the specializer/JIT\n") at src/core/exceptions.c:830
#1  0x00007ffff79ae831 in run_gc (tc=tc@entry=0x5555555e8b90, what_to_do=what_to_do@entry=1 '\001') at src/gc/orchestrate.c:395
#2  0x00007ffff79ae99f in MVM_gc_enter_from_interrupt (tc=tc@entry=0x5555555e8b90) at src/gc/orchestrate.c:618
#3  0x00007ffff79aebe9 in MVM_gc_mark_thread_blocked (tc=tc@entry=0x5555555e8b90) at src/gc/orchestrate.c:297
#4  0x00007ffff79f8da9 in MVM_reentrantmutex_lock (tc=tc@entry=0x5555555e8b90, rm=<optimized out>) at src/6model/reprs/ReentrantMutex.c:136
#5  0x00007ffff7a0f644 in MVM_serialization_demand_object (tc=tc@entry=0x5555555e8b90, sc=<optimized out>, idx=4) at src/6model/serialization.c:2815
#6  0x00007ffff7a0a268 in MVM_sc_get_object (tc=tc@entry=0x5555555e8b90, sc=sc@entry=0x555555bfb260, idx=idx@entry=4) at src/6model/sc.c:185
#7  0x00007ffff7a203f4 in wvalfrom_facts (idx=4, sslot=<optimized out>, tgt_i=<optimized out>, tgt_orig=50, g=0x7ffff0edf4d0, tc=0x5555555e8b90) at src/spesh/facts.c:130
#8  add_bb_facts (tc=tc@entry=0x5555555e8b90, g=g@entry=0x7ffff0edf4d0, bb=0x7ffff1174328, p=p@entry=0x0) at src/spesh/facts.c:633
#9  0x00007ffff7a1f68b in add_bb_facts (tc=tc@entry=0x5555555e8b90, g=g@entry=0x7ffff0edf4d0, bb=<optimized out>, p=p@entry=0x0) at src/spesh/facts.c:753
#10 0x00007ffff7a1f68b in add_bb_facts (tc=tc@entry=0x5555555e8b90, g=g@entry=0x7ffff0edf4d0, bb=<optimized out>, p=p@entry=0x0) at src/spesh/facts.c:753
#11 0x00007ffff7a1f68b in add_bb_facts (tc=tc@entry=0x5555555e8b90, g=g@entry=0x7ffff0edf4d0, bb=<optimized out>, p=p@entry=0x0) at src/spesh/facts.c:753
#12 0x00007ffff7a1f68b in add_bb_facts (tc=tc@entry=0x5555555e8b90, g=g@entry=0x7ffff0edf4d0, bb=<optimized out>, p=p@entry=0x0) at src/spesh/facts.c:753
#13 0x00007ffff7a1f68b in add_bb_facts (tc=tc@entry=0x5555555e8b90, g=g@entry=0x7ffff0edf4d0, bb=<optimized out>, p=p@entry=0x0) at src/spesh/facts.c:753
#14 0x00007ffff7a1f68b in add_bb_facts (tc=tc@entry=0x5555555e8b90, g=g@entry=0x7ffff0edf4d0, bb=<optimized out>, p=p@entry=0x0) at src/spesh/facts.c:753
#15 0x00007ffff7a1f68b in add_bb_facts (tc=tc@entry=0x5555555e8b90, g=g@entry=0x7ffff0edf4d0, bb=<optimized out>, p=p@entry=0x0) at src/spesh/facts.c:753
#16 0x00007ffff7a1f68b in add_bb_facts (tc=tc@entry=0x5555555e8b90, g=g@entry=0x7ffff0edf4d0, bb=<optimized out>, p=p@entry=0x0) at src/spesh/facts.c:753
#17 0x00007ffff7a1f68b in add_bb_facts (tc=tc@entry=0x5555555e8b90, g=g@entry=0x7ffff0edf4d0, bb=<optimized out>, p=p@entry=0x0) at src/spesh/facts.c:753
#18 0x00007ffff7a20a53 in MVM_spesh_facts_discover (tc=tc@entry=0x5555555e8b90, g=g@entry=0x7ffff0edf4d0, p=p@entry=0x0, is_specialized=is_specialized@entry=1) at src/spesh/facts.c:790
#19 0x00007ffff7a2ac6f in MVM_spesh_inline_try_get_graph (tc=tc@entry=0x5555555e8b90, inliner=inliner@entry=0x7ffff01544e0, target_sf=target_sf@entry=0x555558a73528, cand=0x7ffff030cb90, invoke_ins=invoke_ins@entry=0x7ffff00d4ce8, no_inline_reason=no_inline_reason@entry=0x7ffff73bd818, effective_size=0x7ffff73bd814, no_inline_info=0x7ffff73bd820) at src/spesh/inline.c:252
#20 0x00007ffff7a23f34 in optimize_call (tc=tc@entry=0x5555555e8b90, g=g@entry=0x7ffff01544e0, bb=bb@entry=0x7ffff00d5a98, ins=ins@entry=0x7ffff00d4ce8, p=p@entry=0x7ffff014e620, callee_idx=callee_idx@entry=1, arg_info=0x7ffff73bd8d0) at src/spesh/optimize.c:1993
#21 0x00007ffff7a25972 in optimize_bb_switch (tc=tc@entry=0x5555555e8b90, g=g@entry=0x7ffff01544e0, bb=bb@entry=0x7ffff00d5a98, p=p@entry=0x7ffff014e620) at src/spesh/optimize.c:2700
#22 0x00007ffff7a27420 in optimize_bb (tc=0x5555555e8b90, g=0x7ffff01544e0, bb=0x7ffff00d5a98, p=0x7ffff014e620) at src/spesh/optimize.c:2956
#23 0x00007ffff7a2744c in optimize_bb (tc=0x5555555e8b90, g=0x7ffff01544e0, bb=0x7ffff00d5978, p=0x7ffff014e620) at src/spesh/optimize.c:2960
#24 0x00007ffff7a274e8 in optimize_bb (p=0x7ffff014e620, bb=0x7ffff00d5798, g=0x7ffff01544e0, tc=0x5555555e8b90) at src/spesh/optimize.c:2960
#25 MVM_spesh_optimize (tc=tc@entry=0x5555555e8b90, g=g@entry=0x7ffff01544e0, p=p@entry=0x7ffff014e620) at src/spesh/optimize.c:3323
#26 0x00007ffff7a1b0fa in MVM_spesh_candidate_add (tc=tc@entry=0x5555555e8b90, p=0x7ffff014e620) at src/spesh/candidate.c:85
#27 0x00007ffff7a2e301 in worker (tc=0x5555555e8b90, callsite=<optimized out>, args=<optimized out>) at src/spesh/worker.c:16
#28 0x00007ffff7991001 in thread_initial_invoke (tc=0x5555555e8b90, data=<optimized out>) at src/core/threads.c:59
#29 0x00007ffff7968cbc in MVM_interp_run (tc=0x1, tc@entry=0x5555555e8b90, initial_invoke=0x0, invoke_data=0x55555555a2e8, invoke_data@entry=0x5555555ebf10) at src/core/interp.c:137
#30 0x00007ffff7991086 in start_thread (data=0x5555555ebf10) at src/core/threads.c:87
#31 0x00007ffff7420182 in start_thread (arg=<optimized out>) at pthread_create.c:486
#32 0x00007ffff76a3b1f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb)
```

**Comment by dogbert17** [comment]
Is it possible that one of nine's recent changes has fixed this problem?

**Comment by dogbert17** [comment]
I haven't seen that test fail in ages. Perhaps this issue could be closed?

**Comment by lizmat** [comment]
Closing as not reproducible (anymore)
