### ISSUE TITLE
Segfault when running t/spec/S32-io/io-path-extension.t

### ISSUE THREAD

**Issue by Kaiepi** [rakudo/rakudo#3115]
## The Problem
`t/spec/S32-io/io-path-extension.t` segfaults when running it sometimes.

## Expected Behavior
It should always pass.

## Actual Behavior
It segfaults at seemingly random times:
```
t/spec/S32-io/io-path-extension.t                               (Wstat: 139 Tests: 10 Failed: 0)
  Non-zero wait status: 139
  Parse errors: Bad plan.  You planned 283 tests but ran 10.
```

```
bastille% perl6 t/spec/S32-io/io-path-extension.t
1..283
ok 1 - 'foo.txt.tar.gz'.IO.extension \()
ok 2 - 'foo.txt.tar.gz'.IO.extension \(:parts(1))
ok 3 - 'foo.txt.tar.gz'.IO.extension \(:parts(1..1))
ok 4 - 'foo.txt.tar.gz'.IO.extension \(:parts(0..1))
ok 5 - 'foo.txt.tar.gz'.IO.extension \(:parts(2))
ok 6 - 'foo.txt.tar.gz'.IO.extension \(:parts(2..2))
zsh: segmentation fault (core dumped)  perl6 t/spec/S32-io/io-path-extension.t
```

I've never seen this happen before, so it may be new.

## Steps to Reproduce

Run `perl6 t/spec/S32-io/io-path-extension.t`. I tried writing a script to run it until it segfaults, but for some reason the segfault never happens when I do that.

## Environment
* Operating system: 
OpenBSD bastille.kennel.qt 6.5 GENERIC.MP#101 amd64
* Compiler version (`perl6 -v`): 
This is Rakudo version 2019.07.1-127-g916243122b built on MoarVM version 2019.07.1-72-g352ae27e4
implementing Perl 6.d.

**Comment by Kaiepi** [comment]
Manually bisected to https://github.com/MoarVM/MoarVM/commit/4227c7137f8b9edb25a61a79d59d128a5863fc6b

**Comment by niner** [comment]
I'm sorry, I think that result is bogus. The backtrace I get is nowhere near the spesh thread and I have no idea how the MVMROOT could cause a frame's arg context to be zeroed out. Such intermittened errors are notoriously hard to bisect. I've been bitten by that quite a few times.

On August 9, 2019 4:46:41 AM GMT+07:00, Ben Davies <notifications@github.com> wrote:
>Manually bisected to
>https://github.com/MoarVM/MoarVM/commit/4227c7137f8b9edb25a61a79d59d128a5863fc6b
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/rakudo/rakudo/issues/3115#issuecomment-519699545

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Kaiepi** [comment]
Looks like you're probably right. I built MoarVM on master again and tried to trigger the segfault but now it's not happening at all...?

**Comment by niner** [comment]
It doesn't look like any of the GC related issues. Even with fromspace poisoning *ctx is all zeros. If it were in the fromspace it would be full of 0xfe. Maybe it's the ìs copy`trait on `@x` in `mutate`.
```
Thread 1 "perl6-m" received signal SIGSEGV, Segmentation fault.
MVM_interp_run (tc=0x405e70, initial_invoke=0x7ffff7a4517f <toplevel_initial_invoke>, invoke_data=0x4a4408) at src/core/interp.c:3988
3988                    if (ctx->callsite->num_pos != ctx->callsite->arg_count)
(gdb) bt
#0  MVM_interp_run (tc=0x405e70, initial_invoke=0x7ffff7a4517f <toplevel_initial_invoke>, invoke_data=0x4a4408) at src/core/interp.c:3988
#1  0x00007ffff7a452e8 in MVM_vm_run_file (instance=0x405410, filename=0x4053b0 "/home/nine/rakudo/install/share/perl6/runtime/perl6.moarvm") at src/moar.c:445
#2  0x000000000040149c in main ()
(gdb) p *ctx
$1 = {callsite = 0x0, arg_flags = 0x0, args = 0x0, named_used = {byte_array = 0x0, bit_field = 0}, named_used_size = 0, arg_count = 0, num_pos = 0, flag_count = 0}
(gdb) l
3983                    cur_op += 6;
3984                    goto NEXT;
3985                }
3986                OP(paramnamesused): {
3987                    MVMArgProcContext *ctx = &tc->cur_frame->params;
3988                    if (ctx->callsite->num_pos != ctx->callsite->arg_count)
3989                        MVM_args_assert_nameds_used(tc, ctx);
3990                    goto NEXT;
3991                }
3992                OP(getuniname): {
(gdb) call MVM_dump_backtrace(tc)
   at segv.pl6:9  (<ephemeral file>:mutate)
 from segv.pl6:36  (<ephemeral file>:)
 from SETTING::src/core/Any-iterable-methods.pm6:428  (/home/nine/rakudo/install/share/perl6/runtime/CORE.setting.moarvm:push-all)
 from SETTING::src/core/Iterator.pm6:70  (/home/nine/rakudo/install/share/perl6/runtime/CORE.setting.moarvm:push-until-lazy)
 from SETTING::src/core/Array.pm6:286  (/home/nine/rakudo/install/share/perl6/runtime/CORE.setting.moarvm:STORE)
 from segv.pl6:36  (<ephemeral file>:)
 from segv.pl6:29  (<ephemeral file>:MAIN)
 from SETTING::src/core/Main.pm6:317  (/home/nine/rakudo/install/share/perl6/runtime/CORE.setting.moarvm:)
 from SETTING::src/core/Main.pm6:313  (/home/nine/rakudo/install/share/perl6/runtime/CORE.setting.moarvm:)
 from SETTING::src/core/Main.pm6:312  (/home/nine/rakudo/install/share/perl6/runtime/CORE.setting.moarvm:RUN-MAIN)
 from segv.pl6:3  (<ephemeral file>:<unit>)
 from segv.pl6:1  (<ephemeral file>:<unit-outer>)
 from gen/moar/stage2/NQPHLL.nqp:1835  (/home/nine/rakudo/install/share/nqp/lib/NQPHLL.moarvm:eval)
 from gen/moar/stage2/NQPHLL.nqp:2039  (/home/nine/rakudo/install/share/nqp/lib/NQPHLL.moarvm:evalfiles)
 from gen/moar/stage2/NQPHLL.nqp:1969  (/home/nine/rakudo/install/share/nqp/lib/NQPHLL.moarvm:command_eval)
 from src/Perl6/Compiler.nqp:52  (/home/nine/rakudo/install/share/perl6/lib/Perl6/Compiler.moarvm:command_eval)
 from gen/moar/stage2/NQPHLL.nqp:1924  (/home/nine/rakudo/install/share/nqp/lib/NQPHLL.moarvm:command_line)
 from gen/moar/main.nqp:82  (/home/nine/rakudo/install/share/perl6/runtime/perl6.moarvm:MAIN)
 from gen/moar/main.nqp:47  (/home/nine/rakudo/install/share/perl6/runtime/perl6.moarvm:<mainline>)
 from <unknown>:1  (/home/nine/rakudo/install/share/perl6/runtime/perl6.moarvm:<main>)
 from <unknown>:1  (/home/nine/rakudo/install/share/perl6/runtime/perl6.moarvm:<entry>)
(gdb) call MVM_dump_bytecode(tc)
00000      checkarity         1, 1
00001      param_rp_o         loc_1_obj, 0
00002      hllize             loc_2_obj, loc_1_obj
00003      set                loc_1_obj, loc_2_obj
00004      decont             loc_2_obj, loc_1_obj
00005      set                loc_11_obj, loc_2_obj
00006      wval               loc_2_obj, 2, 65
00007      istype             loc_3_int, loc_11_obj, loc_2_obj
00008      unless_i           loc_3_int, label_1(00017)
00009      decont             loc_8_obj, loc_11_obj
00010      findmeth           loc_2_obj, loc_8_obj, 'cache'
00011      prepargs           Callsite_0
00012      arg_o              0, loc_11_obj
00013      invoke_o           loc_2_obj, loc_2_obj
00014      set                loc_1_obj, loc_2_obj
00015      decont             loc_2_obj, loc_1_obj
00016      set                loc_11_obj, loc_2_obj
     label_1:
00017      wval               loc_2_obj, 2, 45
00018      istype             loc_3_int, loc_11_obj, loc_2_obj
00019      assertparamcheck   loc_3_int
00020      wval               loc_2_obj, 1, 42
00021      create             loc_2_obj, loc_2_obj
00022      set                loc_12_obj, loc_2_obj
00023      decont             loc_2_obj, loc_1_obj
00024      decont             loc_9_obj, loc_12_obj
00025      findmeth           loc_8_obj, loc_9_obj, 'STORE'
00026      prepargs           Callsite_1
00027      arg_o              0, loc_12_obj
00028      arg_o              1, loc_2_obj
00029      invoke_o           loc_8_obj, loc_8_obj
00030   -> set                loc_0_obj, loc_12_obj
00031      paramnamesused     
     annotation: segv.pl6:9
```
