### ISSUE TITLE
GCing CStructs with embedded CArrays can crash

### ISSUE THREAD

**Issue by puyawsiht** [rakudo/rakudo#3342]
## The Problem

On my system, this Raku code will crash reliably:

```
use NativeCall;

class Foo is repr('CStruct') {
    has int32 $.a;
    HAS int32 @.b[1] is CArray;
}

for ^∞ {
    say $_;
    Foo.new;
}
```

```
~/raku $ perl6-gdb-m test.p6
0
1
2
[...]
1946
free(): invalid pointer

Thread 1 "moar" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: File or directory not found.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff760d535 in __GI_abort () at abort.c:79
#2  0x00007ffff7674726 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff779a952 "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff767b59a in malloc_printerr (str=str@entry=0x7ffff7798a9b "free(): invalid pointer") at malloc.c:5352
#4  0x00007ffff767d3cc in _int_free (av=<optimized out>, p=<optimized out>, have_lock=<optimized out>) at malloc.c:4181
#5  0x00007ffff7a5ef67 in gc_free () from //home/me/rakudo/lib/libmoar.so
#6  0x00007ffff7a2a7a5 in MVM_gc_collect_free_nursery_uncopied () from //home/me/rakudo/lib/libmoar.so
#7  0x00007ffff7a25fb4 in run_gc () from //home/me/rakudo/lib/libmoar.so
#8  0x00007ffff7a268ff in MVM_gc_enter_from_allocator () from //home/me/rakudo/lib/libmoar.so
#9  0x00007ffff7a26c66 in MVM_gc_allocate_nursery () from //home/me/rakudo/lib/libmoar.so
#10 0x00007ffff7a26e7b in MVM_gc_allocate_object () from //home/me/rakudo/lib/libmoar.so
#11 0x00007ffff7a3c913 in MVM_repr_alloc_init () from //home/me/rakudo/lib/libmoar.so
#12 0x00007ffff7aae52b in MVM_string_ascii_from_buf_nocheck () from //home/me/rakudo/lib/libmoar.so
#13 0x00007ffff7a0d7af in MVM_coerce_i_s () from //home/me/rakudo/lib/libmoar.so
#14 0x00007ffff7adf6e3 in MVM_bigint_to_str () from //home/me/rakudo/lib/libmoar.so
#15 0x00007ffff4a0f0bb in ?? ()
#16 0x00007ffff7f0e4a0 in two_args_callsite () from //home/me/rakudo/lib/libmoar.so
#17 0x0000555555810ef0 in ?? ()
#18 0x0000555555559ca0 in ?? ()
#19 0x00007ffff7f0e4a0 in two_args_callsite () from //home/me/rakudo/lib/libmoar.so
#20 0x0000555555810ef0 in ?? ()
#21 0x00007ffff7a023d9 in MVM_frame_invoke () from //home/me/rakudo/lib/libmoar.so
#22 0x0000555555559ca0 in ?? ()
#23 0x0000555555810ed8 in ?? ()
#24 0x0000555555559ca0 in ?? ()
#25 0x0000000000000000 in ?? ()
```

* Removing either `$.a` or `@.b` from `Foo` stops the crash from happening.
* So does putting `@.b` first.
* Changing the `int32` to something else does not have an effect.
* Changing the size of `@.b` to something else does not have an effect (not even setting it to 0).

## Environment
* Operating system: `Linux brimborium 5.0.0-37-lowlatency #40-Ubuntu SMP PREEMPT Thu Nov 14 01:49:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
* Compiler version (`perl6 -v`): `This is Rakudo Star version 2019.03.1 built on MoarVM version 2019.03
implementing Perl 6.d.`

**Comment by MasterDuke17** [comment]
I can repro with `This is Rakudo version 2019.11-94-g2652d9c59 built on MoarVM version 2019.07.1-412-g716291c21 implementing Perl 6.d.`:
```
<...>
1899
free(): invalid pointer

Thread 1 "perl6" received signal SIGABRT, Aborted.
0x00007ffff74f5f25 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff74f5f25 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff74df897 in abort () from /usr/lib/libc.so.6
#2  0x00007ffff7539258 in __libc_message () from /usr/lib/libc.so.6
#3  0x00007ffff754077a in malloc_printerr () from /usr/lib/libc.so.6
#4  0x00007ffff754214c in _int_free () from /usr/lib/libc.so.6
#5  0x00007ffff7945b27 in MVM_free (p=<optimized out>) at src/core/alloc.h:40
#6  gc_cleanup (data=0x7fffefc868ac, st=<optimized out>, tc=<optimized out>) at src/6model/reprs/CArray.c:140
#7  gc_free (tc=<optimized out>, obj=0x7fffefc86894) at src/6model/reprs/CArray.c:147
#8  0x00007ffff7910721 in MVM_gc_collect_free_nursery_uncopied (executing_thread=executing_thread@entry=0x555555559f90, tc=tc@entry=0x555555559f90, limit=0x7fffefdfcfec) at src/gc/collect.c:625
#9  0x00007ffff790b6ff in finish_gc (is_coordinator=<optimized out>, gen=<optimized out>, tc=0x555555559f90) at src/gc/orchestrate.c:246
#10 run_gc (tc=tc@entry=0x555555559f90, what_to_do=what_to_do@entry=0 '\000') at src/gc/orchestrate.c:448
#11 0x00007ffff790c4df in MVM_gc_enter_from_allocator (tc=tc@entry=0x555555559f90) at src/gc/orchestrate.c:599
#12 0x00007ffff790c801 in MVM_gc_allocate_nursery (tc=0x555555559f90, size=48) at src/gc/allocation.c:37
#13 0x00007ffff790ca2d in MVM_gc_allocate_object (tc=0x555555559f90, st=<optimized out>) at src/gc/allocation.c:93
#14 0x00007ffff79231d3 in MVM_repr_alloc_init (tc=tc@entry=0x555555559f90, type=<optimized out>) at src/6model/reprconv.c:17
#15 0x00007ffff7994247 in MVM_string_concatenate (tc=tc@entry=0x555555559f90, a=<optimized out>, b=<optimized out>) at src/strings/ops.c:912
#16 0x00007ffff7994a4d in MVM_string_replace (tc=0x555555559f90, original=<optimized out>, start=1, count=1, replacement=<optimized out>) at src/strings/ops.c:799
#17 0x00007ffff78c9277 in MVM_interp_run (tc=0x2, tc@entry=0x555555559f90, initial_invoke=0x7fffffffd880, initial_invoke@entry=0x7ffff79d56e0 <toplevel_initial_invoke>, invoke_data=0x7fffffffd880, 
    invoke_data@entry=0x7ffff79d56e0 <toplevel_initial_invoke>) at src/core/interp.c:3940
#18 0x00007ffff79d676f in MVM_vm_run_file (instance=<optimized out>, filename=0x555555559430 "/home/dan/Source/perl6/install/share/perl6/runtime/perl6.moarvm") at src/moar.c:461
#19 0x0000555555555685 in main (argc=<optimized out>, argv=<optimized out>) at src/vm/moar/runner/main.c:378
(gdb)
```

**Comment by MasterDuke17** [comment]
valgrind keeps running, but did give something different (but seemingly related) in the middle:
```
==215436== Memcheck, a memory error detector
==215436== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==215436== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==215436== Command: /home/dan/p6/install/bin/perl6 nc.p6
==215436== 
0
==215436== Invalid write of size 8
==215436==    at 0x4AB3E95: set_ptr_at_offset (CStruct.c:362)
==215436==    by 0x4AB3E95: bind_attribute (CStruct.c:637)
==215436==    by 0x4A43F3C: MVM_interp_run (interp.c:2004)
==215436==    by 0x4B4276E: MVM_vm_run_file (moar.c:461)
==215436==    by 0x109684: main (main.c:378)
==215436==  Address 0xb5419a4 is 4 bytes inside a block of size 8 alloc'd
==215436==    at 0x483AB65: calloc (vg_replace_malloc.c:762)
==215436==    by 0x4AB293B: MVM_calloc (alloc.h:11)
==215436==    by 0x4AB293B: initialize (CStruct.c:413)
==215436==    by 0x4A42887: MVM_interp_run (interp.c:1866)
==215436==    by 0x4B4276E: MVM_vm_run_file (moar.c:461)
==215436==    by 0x109684: main (main.c:378)
==215436== 
1
<...>
```

**Comment by AlexDaniel** [comment]
Seems like it started happening after this: https://github.com/MoarVM/MoarVM/compare/2018.06-375-g46edb6f63...2018.06-380-gac3d3c769
