### ISSUE TITLE
Likely memory corruption in .hyper

### ISSUE THREAD

**Issue by MasterDuke17** [rakudo/rakudo#3475]
t/spec/S07-hyperrace/basics.t now dies with `not ok 84 - hyperized s/…/…/;`. Running just that test directly gives:
```
ok 83 - .hyper preserves order
Use of Nil in string context
  in block  at t/spec/S07-hyperrace/basics.t line 177
not ok 84 - hyperized s/…/…/;
# Failed test 'hyperized s/…/…/;'
# at t/spec/S07-hyperrace/basics.t line 181
# expected: $["++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++"]
#      got: $["++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++"]
A worker in a parallel iteration (hyper or race) initiated here:
  in sub _is_deeply at /home/dan/Source/perl6/rakudo/lib/Test.rakumod (Test) line 675
  in sub is-deeply at /home/dan/Source/perl6/rakudo/lib/Test.rakumod (Test) line 590
  in sub is-deeply at /home/dan/Source/perl6/rakudo/lib/Test.rakumod (Test) line 586
  in block <unit> at t/spec/S07-hyperrace/basics.t line 187

Died at:
    Your printf-style directives specify 0 arguments, but 2 arguments were supplied
      in block  at t/spec/S07-hyperrace/basics.t line 187

# You planned 87 tests, but ran 84
# You failed 1 test of 84
```
and with `--ll-exception`:
```
ok 83 - .hyper preserves order
Use of Nil in string context
  in block  at t/spec/S07-hyperrace/basics.t line 177
not ok 84 - hyperized s/…/…/;
# Failed test 'hyperized s/…/…/;'
# at t/spec/S07-hyperrace/basics.t line 181
# expected: $["++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++"]
#      got: $["++", "++", "++", "++", "", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++", "++"]
Your printf-style directives specify 0 arguments, but 2 arguments were supplied
   at SETTING::src/core.c/Exception.pm6:62  (/home/dan/Source/perl6/rakudo/blib/CORE.c.setting.moarvm:throw)
 from SETTING::src/core.c/Cool.pm6:502  (/home/dan/Source/perl6/rakudo/blib/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/Cool.pm6:501  (/home/dan/Source/perl6/rakudo/blib/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/Cool.pm6:497  (/home/dan/Source/perl6/rakudo/blib/CORE.c.setting.moarvm:)
 from <unknown>:1  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:panic)
 from gen/moar/stage2/NQPHLL.nqp:3072  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:TOP)
 from gen/moar/stage2/QRegex.nqp:1647  (/home/dan/Source/perl6/install/share/nqp/lib/QRegex.moarvm:!reduce)
 from gen/moar/stage2/QRegex.nqp:1590  (/home/dan/Source/perl6/install/share/nqp/lib/QRegex.moarvm:!cursor_pass)
 from <unknown>:1  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:TOP)
 from gen/moar/stage2/QRegex.nqp:2254  (/home/dan/Source/perl6/install/share/nqp/lib/QRegex.moarvm:parse)
 from gen/moar/stage2/NQPHLL.nqp:3522  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:sprintf)
 from SETTING::src/core.c/Cool.pm6:506  (/home/dan/Source/perl6/rakudo/blib/CORE.c.setting.moarvm:sprintf)
 from t/spec/S07-hyperrace/basics.t:187  (<ephemeral file>:)
 from SETTING::src/core.c/Rakudo/Internals/HyperRaceSharedImpl.pm6:61  (/home/dan/Source/perl6/rakudo/blib/CORE.c.setting.moarvm:process-batch)
 from SETTING::src/core.c/Rakudo/Internals/HyperPipeline.pm6:73  (/home/dan/Source/perl6/rakudo/blib/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/Rakudo/Internals/HyperPipeline.pm6:73  (/home/dan/Source/perl6/rakudo/blib/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/Rakudo/Internals/HyperPipeline.pm6:69  (/home/dan/Source/perl6/rakudo/blib/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/Promise.pm6:267  (/home/dan/Source/perl6/rakudo/blib/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/ThreadPoolScheduler.pm6:896  (/home/dan/Source/perl6/rakudo/blib/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/ThreadPoolScheduler.pm6:242  (/home/dan/Source/perl6/rakudo/blib/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/ThreadPoolScheduler.pm6:236  (/home/dan/Source/perl6/rakudo/blib/CORE.c.setting.moarvm:run-one)
 from SETTING::src/core.c/ThreadPoolScheduler.pm6:278  (/home/dan/Source/perl6/rakudo/blib/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/Thread.pm6:54  (/home/dan/Source/perl6/rakudo/blib/CORE.c.setting.moarvm:THREAD-ENTRY)
```
It's a little hard to see, but the 'got: ' has a `<snip>, "++", "", "++", <snip>`
@lizmat confirmed it was caused by https://github.com/rakudo/rakudo/commit/50ca2ed98668c00038af87239dedce48e0d2ecc3, so pinging @jnthn

**Comment by jnthn** [comment]
Don't think it's memory corruption, just screwed closure handling somehow...will take a look at the code it spits out tomorrow. I can repro it now, just doesn't happen every time, and my spectest run after the change was "lucky".

**Comment by MasterDuke17** [comment]
Don't know if this helps:
```
ok 71 - .hyper preserves order
Use of Nil in string context
  in block  at hb.t line 163
not ok 72 - hyperized s/…/…/;

Thread 1 "moar" hit Breakpoint 1, MVM_exception_die (tc=0x555555559da0, str=, rr=0x555555ad7218) at src/core/exceptions.c:720
720         MVMROOT(tc, str, {
(gdb) bt
#0  MVM_exception_die (tc=0x555555559da0, str=, rr=0x555555ad7218) at src/core/exceptions.c:720
#1  0x00007ffff78d5195 in MVM_interp_run (tc=tc@entry=0x555555559da0, initial_invoke=0x7ffff543d3c2, invoke_data=0x555555ea22c0, invoke_data@entry=0x7ffff79d3c60 <toplevel_initial_invoke>) at src/core/interp.c:1349
#2  0x00007ffff79d4cff in MVM_vm_run_file (instance=<optimized out>, filename=0x7fffffffe7ac "/home/dan/Source/perl6/rakudo/perl6.moarvm") at src/moar.c:463
#3  0x0000555555555760 in main (argc=10, argv=0x7fffffffe308) at src/main.c:305
(gdb) call MVM_dump_backtrace(tc)
   at SETTING::src/core.c/CallFrame.pm6:57  (/home/dan/Source/perl6/rakudo/blib/CORE.c.setting.moarvm:callframe)
 from /home/dan/Source/perl6/rakudo/lib/Test.rakumod (Test):743  (/home/dan/Source/perl6/rakudo/lib/.precomp/B3CEE7678CD4F7E162EDBECCFC791DEF1846C847/64/640AB2BAE07BEDC4C163F679A746F7AB7FB5D1FA:)
 from /home/dan/Source/perl6/rakudo/lib/Test.rakumod (Test):737  (/home/dan/Source/perl6/rakudo/lib/.precomp/B3CEE7678CD4F7E162EDBECCFC791DEF1846C847/64/640AB2BAE07BEDC4C163F679A746F7AB7FB5D1FA:proclaim)
 from /home/dan/Source/perl6/rakudo/lib/Test.rakumod (Test):591  (/home/dan/Source/perl6/rakudo/lib/.precomp/B3CEE7678CD4F7E162EDBECCFC791DEF1846C847/64/640AB2BAE07BEDC4C163F679A746F7AB7FB5D1FA:is-deeply)
 from hb.t:167  (<ephemeral file>:)
 from hb.t:157  (<ephemeral file>:<unit>)
 from hb.t:1  (<ephemeral file>:<unit-outer>)
 from gen/moar/stage2/NQPHLL.nqp:1913  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:eval)
 from gen/moar/stage2/NQPHLL.nqp:2118  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:evalfiles)
 from gen/moar/stage2/NQPHLL.nqp:2048  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:command_eval)
 from gen/moar/Compiler.nqp:55  (/home/dan/Source/perl6/rakudo/blib/Perl6/Compiler.moarvm:command_eval)
 from gen/moar/stage2/NQPHLL.nqp:2003  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:command_line)
 from gen/moar/perl6.nqp:127  (/home/dan/Source/perl6/rakudo/perl6.moarvm:MAIN)
 from gen/moar/perl6.nqp:92  (/home/dan/Source/perl6/rakudo/perl6.moarvm:<mainline>)
 from <unknown>:1  (/home/dan/Source/perl6/rakudo/perl6.moarvm:<main>)
 from <unknown>:1  (/home/dan/Source/perl6/rakudo/perl6.moarvm:<entry>)
(gdb)
```
where hb.t is a slightly stripped down t/spec/S07-hyperrace/basics.t and line 167 is `is-deeply @a, [‘++’ xx 100], ‘hyperized s/…/…/;’`.
