### ISSUE TITLE
The module p6-concurrent-queue has flapping tests

### ISSUE THREAD

**Issue by dogbert17** [rakudo/rakudo#3562]
p6-concurrent-queue contains a flapping test, here's what it tends to look like:

    dogbert@dogbert-VirtualBox ~/repos/p6-concurrent-queue $ perl6 -v
    This is Rakudo version 2020.02.1-233-g439b860 built on MoarVM version 2020.02.1-47-g3c3ad06
    implementing Raku 6.d.
    dogbert@dogbert-VirtualBox ~/repos/p6-concurrent-queue $  perl6 -Ilib t/stress.t 
    ok 1 - Correct sum of dequeued values (1)
    ok 2 - Correct sum of dequeued values (2)
    ok 3 - Correct sum of dequeued values (3)
    ok 4 - Correct sum of dequeued values (4)
    1..4
    dogbert@dogbert-VirtualBox ~/repos/p6-concurrent-queue $ MVM_SPESH_DISABLE=1  perl6 -Ilib t/stress.t 
    not ok 1 - Correct sum of dequeued values (1)
    # Failed test 'Correct sum of dequeued values (1)'
    # at t/stress.t line 37
    # expected: '1249975000'
    #      got: '563947974'
    not ok 2 - Correct sum of dequeued values (2)
    # Failed test 'Correct sum of dequeued values (2)'
    # at t/stress.t line 37
    # expected: '1249975000'
    #      got: '660205907'
    not ok 3 - Correct sum of dequeued values (3)
    # Failed test 'Correct sum of dequeued values (3)'
    # at t/stress.t line 37
    # expected: '1249975000'
    #      got: '899124985'
    not ok 4 - Correct sum of dequeued values (4)
    # Failed test 'Correct sum of dequeued values (4)'
    # at t/stress.t line 37
    # expected: '1249975000'
    #      got: '838875558'
    1..4
    # You failed 4 tests of 4
    
running with a small nursery, 4k in this case, often looks like this
    
    dogbert@dogbert-VirtualBox ~/repos/p6-concurrent-queue $ MVM_SPESH_DISABLE=1  perl6-gdb-m -Ilib t/stress.t 
    ================================================================================================
    This is Rakudo running in the  debugger, which often allows the user to generate useful back-
    traces to debug or report issues in Rakudo, the MoarVM backend or the currently running code.
    
    This Rakudo version is 2020.02.1.233.g.439.b.860 built on MoarVM version 2020.02.1.47.g.3.c.3.ad.06,
    running on linuxmint (18.3.Sylvia) / linux
    
    Type `bt full` to generate a backtrace if applicable, type `q` to quit or `help` for help.
    ------------------------------------------------------------------------------------------------
    Reading symbols from /home/dogbert/.rakudobrew/versions/moar-master/install/bin/rakudo-m...(no debugging symbols found)...done.
    Starting program: /home/dogbert/.rakudobrew/versions/moar-master/install/bin/rakudo-m -Ilib t/stress.t
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
    [New Thread 0x7ffff4951700 (LWP 18898)]
    [New Thread 0x7fffeffff700 (LWP 18899)]
    [New Thread 0x7fffef7fe700 (LWP 18900)]
    [New Thread 0x7fffeeffd700 (LWP 18901)]
    [New Thread 0x7fffee7fc700 (LWP 18902)]
    *** Error in `-Ilib': malloc(): smallbin double linked list corrupted: 0x00007fffe420e710 ***
    ======= Backtrace: =========
    /lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7ffff6f0b7e5]
    /lib/x86_64-linux-gnu/libc.so.6(+0x82651)[0x7ffff6f16651]
    /lib/x86_64-linux-gnu/libc.so.6(__libc_malloc+0x54)[0x7ffff6f18184]
    /lib/x86_64-linux-gnu/libc.so.6(realloc+0x358)[0x7ffff6f18a18]
    //home/dogbert/.rakudobrew/versions/moar-master/install/lib/libmoar.so(+0x27192d)[0x7ffff74cf92d]
    //home/dogbert/.rakudobrew/versions/moar-master/install/lib/libmoar.so(+0x27580e)[0x7ffff74d380e]
    //home/dogbert/.rakudobrew/versions/moar-master/install/lib/libmoar.so(+0x27239d)[0x7ffff74d039d]
    //home/dogbert/.rakudobrew/versions/moar-master/install/lib/libmoar.so(MVM_gc_collect+0x49f)[0x7ffff74cff76]
    //home/dogbert/.rakudobrew/versions/moar-master/install/lib/libmoar.so(+0x26619b)[0x7ffff74c419b]
    //home/dogbert/.rakudobrew/versions/moar-master/install/lib/libmoar.so(MVM_gc_enter_from_allocator+0x444)[0x7ffff74c4873]
    //home/dogbert/.rakudobrew/versions/moar-master/install/lib/libmoar.so(MVM_gc_allocate_nursery+0x70)[0x7ffff74c50ef]
    //home/dogbert/.rakudobrew/versions/moar-master/install/lib/libmoar.so(+0x266eea)[0x7ffff74c4eea]
    //home/dogbert/.rakudobrew/versions/moar-master/install/lib/libmoar.so(MVM_gc_allocate_zeroed+0x23)[0x7ffff74c5178]
    //home/dogbert/.rakudobrew/versions/moar-master/install/lib/libmoar.so(MVM_gc_allocate_object+0x3b)[0x7ffff74c551b]
    //home/dogbert/.rakudobrew/versions/moar-master/install/lib/libmoar.so(MVM_repr_alloc_init+0x43)[0x7ffff74f2346]
    //home/dogbert/.rakudobrew/versions/moar-master/install/lib/libmoar.so(+0x341b8d)[0x7ffff759fb8d]
    //home/dogbert/.rakudobrew/versions/moar-master/install/lib/libmoar.so(+0x341d5b)[0x7ffff759fd5b]
    //home/dogbert/.rakudobrew/versions/moar-master/install/lib/libmoar.so(MVM_spesh_plugin_resolve+0x86)[0x7ffff75a1682]
    //home/dogbert/.rakudobrew/versions/moar-master/install/lib/libmoar.so(MVM_interp_run+0x2bd04)[0x7ffff7477d49]
    //home/dogbert/.rakudobrew/versions/moar-master/install/lib/libmoar.so(+0x238417)[0x7ffff7496417]
    /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba)[0x7ffff69756ba]
    /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7ffff6f9b41d]
    ======= Memory map: ========
    00400000-00402000 r-xp 00000000 08:01 54568                              /home/dogbert/.rakudobrew/versions/moar-master/install/bin/rakudo-m
    00601000-00602000 r--p 00001000 08:01 54568                              /home/dogbert/.rakudobrew/versions/moar-master/install/bin/rakudo-m
    00602000-00603000 rw-p 00002000 08:01 54568                              /home/dogbert/.rakudobrew/versions/moar-master/install/bin/rakudo-m
    00603000-03c60000 rw-p 00000000 00:00 0                                  [heap]
    7fffd8000000-7fffd903f000 rw-p 00000000 00:00 0 
    7fffd903f000-7fffdc000000 ---p 00000000 00:00 0 
    7fffdc000000-7fffdc021000 rw-p 00000000 00:00 0 
    7fffdc021000-7fffe0000000 ---p 00000000 00:00 0 
    7fffe0000000-7fffe1011000 rw-p 00000000 00:00 0 
    7fffe1011000-7fffe4000000 ---p 00000000 00:00 0 
    7fffe4000000-7fffe5622000 rw-p 00000000 00:00 0 
    7fffe5622000-7fffe8000000 ---p 00000000 00:00 0 
    7fffe8000000-7fffe80ef000 rw-p 00000000 00:00 0 
    7fffe80ef000-7fffec000000 ---p 00000000 00:00 0 
    7fffedde6000-7fffeddfc000 r-xp 00000000 08:01 137373                     /lib/x86_64-linux-gnu/libgcc_s.so.1
    7fffeddfc000-7fffedffb000 ---p 00016000 08:01 137373                     /lib/x86_64-linux-gnu/libgcc_s.so.1
    7fffedffb000-7fffedffc000 rw-p 00015000 08:01 137373                     /lib/x86_64-linux-gnu/libgcc_s.so.1
    7fffedffc000-7fffedffd000 ---p 00000000 00:00 0 
    7fffedffd000-7fffee7fd000 rw-p 00000000 00:00 0 
    7fffee7fd000-7fffee7fe000 ---p 00000000 00:00 0 
    7fffee7fe000-7fffeeffe000 rw-p 00000000 00:00 0 
    7fffeeffe000-7fffeefff000 ---p 00000000 00:00 0 
    7fffeefff000-7fffef7ff000 rw-p 00000000 00:00 0 
    7fffef7ff000-7fffef800000 ---p 00000000 00:00 0 
    7fffef800000-7ffff0000000 rw-p 00000000 00:00 0 
    7ffff0000000-7ffff0fec000 rw-p 00000000 00:00 0 
    7ffff0fec000-7ffff4000000 ---p 00000000 00:00 0 
    7ffff4151000-7ffff4152000 ---p 00000000 00:00 0 
    7ffff4152000-7ffff4952000 rw-p 00000000 00:00 0 
    7ffff4952000-7ffff497b000 r--p 00000000 08:01 16719                      /home/dogbert/.rakudobrew/versions/moar-master/install/share/perl6/core/precomp/556505B1BF14963F5C059582A55DA6ED842F0686/2D/2D4A7CA10695CD2B374573413D261A660E282E2A
    7ffff497b000-7ffff4983000 r--p 00000000 08:01 575301                     /home/dogbert/repos/p6-concurrent-queue/lib/.precomp/556505B1BF14963F5C059582A55DA6ED842F0686/FF/FF2AF0FC450A43872BFD893A9586082901190389
    7ffff4983000-7ffff4ae3000 rw-p 00000000 00:00 0 
    7ffff4ae3000-7ffff4b3a000 r--p 00000000 08:01 8946                       /home/dogbert/.rakudobrew/versions/moar-master/install/share/perl6/lib/Perl6/Metamodel.moarvm
    7ffff4b3a000-7ffff4b75000 r--p 00000000 08:01 8948                       /home/dogbert/.rakudobrew/versions/moar-master/install/share/perl6/lib/Perl6/BOOTSTRAP/v6c.moarvm
    7ffff4b75000-7ffff5a2f000 r--p 00000000 08:01 8954                       /home/dogbert/.rakudobrew/versions/moar-master/install/share/perl6/runtime/CORE.c.setting.moarvm
    7ffff5a2f000-7ffff5a3d000 r--p 00000000 08:01 8956                       /home/dogbert/.rakudobrew/versions/moar-master/install/share/perl6/runtime/CORE.d.setting.moarvm
    7ffff5a3d000-7ffff5a42000 r-xp 00000000 08:01 54564                      /home/dogbert/.rakudobrew/versions/moar-master/install/share/perl6/runtime/dynext/libperl6_ops_moar.so
    7ffff5a42000-7ffff5c41000 ---p 00005000 08:01 54564                      /home/dogbert/.rakudobrew/versions/moar-master/install/share/perl6/runtime/dynext/libperl6_ops_moar.so
    7ffff5c41000-7ffff5c42000 r--p 00004000 08:01 54564                      /home/dogbert/.rakudobrew/versions/moar-master/install/share/perl6/runtime/dynext/libperl6_ops_moar.so
    7ffff5c42000-7ffff5c43000 rw-p 00005000 08:01 54564                      /home/dogbert/.rakudobrew/versions/moar-master/install/share/perl6/runtime/dynext/libperl6_ops_moar.so
    7ffff5c43000-7ffff5c72000 r--p 00000000 08:01 8940                       /home/dogbert/.rakudobrew/versions/moar-master/install/share/perl6/lib/Perl6/Optimizer.moarvm
    7ffff5c72000-7ffff5d92000 rw-p 00000000 00:00 0 
    7ffff5d92000-7ffff5de6000 r--p 00000000 08:01 8931                       /home/dogbert/.rakudobrew/versions/moar-master/install/share/perl6/lib/Perl6/World.moarvm
    7ffff5de6000-7ffff5e10000 r--p 00000000 08:01 8942                       /home/dogbert/.rakudobrew/versions/moar-master/install/share/perl6/lib/Perl6/Pod.moarvm
    7ffff5e10000-7ffff5efe000 r--p 00000000 08:01 8938                       /home/dogbert/.rakudobrew/versions/moar-master/install/share/perl6/lib/Perl6/Actions.moarvm
    7ffff5efe000-7ffff5f37000 r--p 00000000 08:01 54480                      /home/dogbert/.rakudobrew/versions/moar-master/install/share/nqp/lib/NQPP5QRegex.moarvm
    7ffff5f37000-7ffff64bf000 r--p 00000000 08:01 8934                       /home/dogbert/.rakudobrew/versions/moar-master/install/share/perl6/lib/Perl6/Grammar.moarvm
    7ffff64bf000-7ffff6562000 r--p 00000000 08:01 54475                      /home/dogbert/.rakudobrew/versions/moar-master/install/share/nqp/lib/MASTOps.moarvm
    7ffff6562000-7ffff6565000 r-xp 00000000 08:01 166227                     /lib/x86_64-linux-gnu/libdl-2.23.so
    7ffff6565000-7ffff6764000 ---p 00003000 08:01 166227                     /lib/x86_64-linux-gnu/libdl-2.23.so
    7ffff6764000-7ffff6765000 r--p 00002000 08:01 166227                     /lib/x86_64-linux-gnu/libdl-2.23.so
    7ffff6765000-7ffff6766000 rw-p 00003000 08:01 166227                     /lib/x86_64-linux-gnu/libdl-2.23.so
    7ffff6766000-7ffff676d000 r-xp 00000000 08:01 169733                     /lib/x86_64-linux-gnu/librt-2.23.so
    7ffff676d000-7ffff696c000 ---p 00007000 08:01 169733                     /lib/x86_64-linux-gnu/librt-2.23.so
    7ffff696c000-7ffff696d000 r--p 00006000 08:01 169733                     /lib/x86_64-linux-gnu/librt-2.23.so
    7ffff696d000-7ffff696e000 rw-p 00007000 08:01 169733                     /lib/x86_64-linux-gnu/librt-2.23.so
    7ffff696e000-7ffff6986000 r-xp 00000000 08:01 166224                     /lib/x86_64-linux-gnu/libpthread-2.23.so
    7ffff6986000-7ffff6b85000 ---p 00018000 08:01 166224                     /lib/x86_64-linux-gnu/libpthread-2.23.so
    7ffff6b85000-7ffff6b86000 r--p 00017000 08:01 166224                     /lib/x86_64-linux-gnu/libpthread-2.23.so
    7ffff6b86000-7ffff6b87000 rw-p 00018000 08:01 166224                     /lib/x86_64-linux-gnu/libpthread-2.23.so
    7ffff6b87000-7ffff6b8b000 rw-p 00000000 00:00 0 
    7ffff6b8b000-7ffff6c93000 r-xp 00000000 08:01 131112                     /lib/x86_64-linux-gnu/libm-2.23.so
    7ffff6c93000-7ffff6e92000 ---p 00108000 08:01 131112                     /lib/x86_64-linux-gnu/libm-2.23.so
    7ffff6e92000-7ffff6e93000 r--p 00107000 08:01 131112                     /lib/x86_64-linux-gnu/libm-2.23.so
    7ffff6e93000-7ffff6e94000 rw-p 00108000 08:01 131112                     /lib/x86_64-linux-gnu/libm-2.23.so
    7ffff6e94000-7ffff7054000 r-xp 00000000 08:01 166225                     /lib/x86_64-linux-gnu/libc-2.23.so
    7ffff7054000-7ffff7254000 ---p 001c0000 08:01 166225                     /lib/x86_64-linux-gnu/libc-2.23.so
    7ffff7254000-7ffff7258000 r--p 001c0000 08:01 166225                     /lib/x86_64-linux-gnu/libc-2.23.so
    7ffff7258000-7ffff725a000 rw-p 001c4000 08:01 166225                     /lib/x86_64-linux-gnu/libc-2.23.so
    7ffff725a000-7ffff725e000 rw-p 00000000 00:00 0 
    7ffff725e000-7ffff7a19000 r-xp 00000000 08:01 1015                       /home/dogbert/.rakudobrew/versions/moar-master/install/lib/libmoar.so
    7ffff7a19000-7ffff7c19000 ---p 007bb000 08:01 1015                       /home/dogbert/.rakudobrew/versions/moar-master/install/lib/libmoar.so
    7ffff7c19000-7ffff7c61000 r--p 007bb000 08:01 1015                       /home/dogbert/.rakudobrew/versions/moar-master/install/lib/libmoar.so
    7ffff7c61000-7ffff7dd6000 rw-p 00803000 08:01 1015                       /home/dogbert/.rakudobrew/versions/moar-master/install/lib/libmoar.so
    7ffff7dd6000-7ffff7dd7000 rw-p 00000000 00:00 0 
    7ffff7dd7000-7ffff7dfd000 r-xp 00000000 08:01 166223                     /lib/x86_64-linux-gnu/ld-2.23.so
    7ffff7dfd000-7ffff7dff000 r--p 00000000 08:01 8950                       /home/dogbert/.rakudobrew/versions/moar-master/install/share/perl6/lib/Perl6/BOOTSTRAP/v6d.moarvm
    7ffff7dff000-7ffff7e05000 r--p 00000000 08:01 8944                       /home/dogbert/.rakudobrew/versions/moar-master/install/share/perl6/lib/Perl6/Compiler.moarvm
    7ffff7e05000-7ffff7e0b000 r--p 00000000 08:01 8929                       /home/dogbert/.rakudobrew/versions/moar-master/install/share/perl6/lib/Perl6/ModuleLoader.moarvm
    7ffff7e0b000-7ffff7e1b000 r--p 00000000 08:01 8936                       /home/dogbert/.rakudobrew/versions/moar-master/install/share/perl6/lib/Perl6/Ops.moarvm
    7ffff7e1b000-7ffff7e32000 r--p 00000000 08:01 54476                      /home/dogbert/.rakudobrew/versions/moar-master/install/share/nqp/lib/MASTNodes.moarvm
    7ffff7e32000-7ffff7eae000 r--p 00000000 08:01 54477                      /home/dogbert/.rakudobrew/versions/moar-master/install/share/nqp/lib/QAST.moarvm
    7ffff7eae000-7ffff7f0a000 r--p 00000000 08:01 54474                      /home/dogbert/.rakudobrew/versions/moar-master/install/share/nqp/lib/NQPHLL.moarvm
    7ffff7f0a000-7ffff7f22000 r--p 00000000 08:01 54471                      /home/dogbert/.rakudobrew/versions/moar-master/install/share/nqp/lib/QASTNode.moarvm
    7ffff7f22000-7ffff7f44000 r--p 00000000 08:01 54472                      /home/dogbert/.rakudobrew/versions/moar-master/install/share/nqp/lib/QRegex.moarvm
    7ffff7f44000-7ffff7fa5000 r--p 00000000 08:01 54478                      /home/dogbert/.rakudobrew/versions/moar-master/install/share/nqp/lib/NQPP6QRegex.moarvm
    7ffff7fa5000-7ffff7fb8000 r--p 00000000 08:01 54465                      /home/dogbert/.rakudobrew/versions/moar-master/install/share/nqp/lib/nqpmo.moarvm
    7ffff7fb8000-7ffff7fdf000 rw-p 00000000 00:00 0 
    7ffff7fdf000-7ffff7ff1000 r--p 00000000 08:01 54469                      /home/dogbert/.rakudobrew/versions/moar-master/install/share/nqp/lib/NQPCORE.setting.moarvm
    7ffff7ff1000-7ffff7ff4000 r--p 00000000 08:01 54467                      /home/dogbert/.rakudobrew/versions/moar-master/install/share/nqp/lib/ModuleLoader.moarvm
    7ffff7ff4000-7ffff7ff7000 r--p 00000000 08:01 8963                       /home/dogbert/.rakudobrew/versions/moar-master/install/share/perl6/runtime/perl6.moarvm
    7ffff7ff7000-7ffff7ff8000 rw-p 00000000 00:00 0 
    7ffff7ff8000-7ffff7ffa000 r--p 00000000 00:00 0                          [vvar]
    7ffff7ffa000-7ffff7ffc000 r-xp 00000000 00:00 0                          [vdso]
    7ffff7ffc000-7ffff7ffd000 r--p 00025000 08:01 166223                     /lib/x86_64-linux-gnu/ld-2.23.so
    7ffff7ffd000-7ffff7ffe000 rw-p 00026000 08:01 166223                     /lib/x86_64-linux-gnu/ld-2.23.so
    7ffff7ffe000-7ffff7fff000 rw-p 00000000 00:00 0 
    7ffffffde000-7ffffffff000 rw-p 00000000 00:00 0                          [stack]
    ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
    
    Thread 5 "rakudo-m" received signal SIGABRT, Aborted.
    [Switching to Thread 0x7fffeeffd700 (LWP 18901)]
    0x00007ffff6ec9428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
    54	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
    (gdb) bt
    #0  0x00007ffff6ec9428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
    #1  0x00007ffff6ecb02a in __GI_abort () at abort.c:89
    #2  0x00007ffff6f0b7ea in __libc_message (do_abort=do_abort@entry=2, fmt=fmt@entry=0x7ffff7024ed8 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
    #3  0x00007ffff6f16651 in malloc_printerr (ar_ptr=0x7fffeeffaf20, ptr=0x7fffe420e710, str=0x7ffff7025308 "malloc(): smallbin double linked list corrupted", action=3) at malloc.c:5006
    #4  _int_malloc (av=av@entry=0x7fffe4000020, bytes=bytes@entry=16) at malloc.c:3386
    #5  0x00007ffff6f18184 in __GI___libc_malloc (bytes=16) at malloc.c:2913
    #6  0x00007ffff6f18a18 in __GI___libc_realloc (oldmem=0x0, bytes=16) at malloc.c:2994
    #7  0x00007ffff74cf92d in MVM_realloc (p=0x0, size=16) at src/core/alloc.h:20
    #8  0x00007ffff74d380e in pass_work_item (tc=0x7fffe80a5390, wtp=0x7fffeeffb140, item_ptr=0x7fffe4d7bf90) at src/gc/collect.c:495
    #9  0x00007ffff74d039d in process_worklist (tc=0x7fffe80a5390, worklist=0x7fffe42b1410, wtp=0x7fffeeffb140, gen=0 '\000') at src/gc/collect.c:240
    #10 0x00007ffff74cff76 in MVM_gc_collect (tc=0x7fffe80a5390, what_to_do=0 '\000', gen=0 '\000') at src/gc/collect.c:134
    #11 0x00007ffff74c419b in run_gc (tc=0x7fffe80a5390, what_to_do=0 '\000') at src/gc/orchestrate.c:444
    #12 0x00007ffff74c4873 in MVM_gc_enter_from_allocator (tc=0x7fffe80a5390) at src/gc/orchestrate.c:599
    #13 0x00007ffff74c50ef in MVM_gc_allocate_nursery (tc=0x7fffe80a5390, size=56) at src/gc/allocation.c:37
    #14 0x00007ffff74c4eea in MVM_gc_allocate (tc=0x7fffe80a5390, size=56) at src/gc/allocation.h:18
    #15 0x00007ffff74c5178 in MVM_gc_allocate_zeroed (tc=0x7fffe80a5390, size=56) at src/gc/allocation.c:56
    #16 0x00007ffff74c551b in MVM_gc_allocate_object (tc=0x7fffe80a5390, st=0x6568e0) at src/gc/allocation.c:93
    #17 0x00007ffff74f2346 in MVM_repr_alloc_init (tc=0x7fffe80a5390, type=0x662cf0) at src/6model/reprconv.c:17
    #18 0x00007ffff759fb8d in evaluate_guards (tc=0x7fffe80a5390, gs=0x7ffff003a668, callsite=0x7ffff7c64520 <two_args_callsite>, guard_offset=0x7fffeeffb41a) at src/spesh/plugin.c:95
    #19 0x00007ffff759fd5b in resolve_using_guards (tc=0x7fffe80a5390, cur_position=830, callsite=0x7ffff7c64520 <two_args_callsite>, guard_offset=0x7fffeeffb41a, sf=0x21aa090) at src/spesh/plugin.c:129
    #20 0x00007ffff75a1682 in MVM_spesh_plugin_resolve (tc=0x7fffe80a5390, name=0x3bab2f0, result=0x7fffe4d7bf88, op_addr=0x7ffff4980cc3 "\034\003\f", next_addr=0x7ffff4980ccb "\177", 
        callsite=0x7ffff7c64520 <two_args_callsite>) at src/spesh/plugin.c:445
    #21 0x00007ffff7477d49 in MVM_interp_run (tc=0x7fffe80a5390, initial_invoke=0x7ffff74962ce <thread_initial_invoke>, invoke_data=0x7fffe807b1d0) at src/core/interp.c:5441
    #22 0x00007ffff7496417 in start_thread (data=0x7fffe807b1d0) at src/core/threads.c:87
    #23 0x00007ffff69756ba in start_thread (arg=0x7fffeeffd700) at pthread_create.c:333
    #24 0x00007ffff6f9b41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
    (gdb) info threads
      Id   Target Id         Frame 
      1    Thread 0x7ffff7fda700 (LWP 18894) "rakudo-m" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
      2    Thread 0x7ffff4951700 (LWP 18898) "rakudo-m" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
      3    Thread 0x7fffeffff700 (LWP 18899) "rakudo-m" 0x00007ffff6f6030d in nanosleep () at ../sysdeps/unix/syscall-template.S:84
      4    Thread 0x7fffef7fe700 (LWP 18900) "rakudo-m" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
    * 5    Thread 0x7fffeeffd700 (LWP 18901) "rakudo-m" 0x00007ffff6ec9428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
      6    Thread 0x7fffee7fc700 (LWP 18902) "rakudo-m" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
    (gdb)

**Comment by dogbert17** [comment]
Fixed sometime after release 2020.06, closing.
