### ISSUE TITLE
[JVM] UnwindException for using gather/take with last in some loop constructs

### ISSUE THREAD

**Issue by usev6** [rakudo/rakudo#3634]
There is a long standing problem on the JVM backend that gather/take in combination with last and different loop constructs lead to an UnwindException. This was reported back in 2015 as https://rt-archive.perl.org/perl6/Ticket/Display.html?id=124279.

Since this is a severe problem (among other things it prevents the installation of ```zef```), I'm opening this issue in favor of [the old one in the old-issue-tracker repo](https://github.com/Raku/old-issue-tracker/issues/3777).

Interestingly, the code snippet from the original report works nowadays:
```
$ ./rakudo-j -e 'gather loop { take my $foo; last; }; say "alive"'
alive
```

But various other loop constructs explode with an UnwindException:
```
$ ./rakudo-j -e 'gather for ^1 { take my $foo; last; }'
Exception in thread "main" org.perl6.nqp.runtime.UnwindException
	at org.perl6.nqp.runtime.ThreadContext.<init>(ThreadContext.java:127)
	at org.perl6.nqp.runtime.GlobalContext.getCurrentThreadContext(GlobalContext.java:348)
	at org.perl6.nqp.runtime.GlobalContext.<init>(GlobalContext.java:253)
	at org.perl6.nqp.runtime.CompilationUnit.enterFromMain(CompilationUnit.java:56)
	at perl6.main(gen/jvm/rakudo.nqp)
$ ./rakudo-j -e 'gather while 1 { take my $foo; last; }'
Exception in thread "main" org.perl6.nqp.runtime.UnwindException
	at org.perl6.nqp.runtime.ThreadContext.<init>(ThreadContext.java:127)
	at org.perl6.nqp.runtime.GlobalContext.getCurrentThreadContext(GlobalContext.java:348)
	at org.perl6.nqp.runtime.GlobalContext.<init>(GlobalContext.java:253)
	at org.perl6.nqp.runtime.CompilationUnit.enterFromMain(CompilationUnit.java:56)
	at perl6.main(gen/jvm/rakudo.nqp)
$ ./rakudo-j -e 'gather repeat { take my $foo; last; } until 0'
Exception in thread "main" org.perl6.nqp.runtime.UnwindException
	at org.perl6.nqp.runtime.ThreadContext.<init>(ThreadContext.java:127)
	at org.perl6.nqp.runtime.GlobalContext.getCurrentThreadContext(GlobalContext.java:348)
	at org.perl6.nqp.runtime.GlobalContext.<init>(GlobalContext.java:253)
	at org.perl6.nqp.runtime.CompilationUnit.enterFromMain(CompilationUnit.java:56)
	at perl6.main(gen/jvm/rakudo.nqp)
```

**Comment by usev6** [comment]
Oh, it's the optimizer that optimizes the UnwindException away in the ```loop``` case. It works with ```--optimize=2``` but fails with ```--optimize=1```:
```
$ ./rakudo-j --optimize=2 -e 'gather loop { take my $foo; last; }; say "alive"'
alive
$ ./rakudo-j --optimize=1 -e 'gather loop { take my $foo; last; }; say "alive"'
Exception in thread "main" org.perl6.nqp.runtime.UnwindException
	at org.perl6.nqp.runtime.ThreadContext.<init>(ThreadContext.java:127)
	at org.perl6.nqp.runtime.GlobalContext.getCurrentThreadContext(GlobalContext.java:348)
	at org.perl6.nqp.runtime.GlobalContext.<init>(GlobalContext.java:253)
	at org.perl6.nqp.runtime.CompilationUnit.enterFromMain(CompilationUnit.java:56)
	at perl6.main(gen/jvm/rakudo.nqp)
```

**Comment by usev6** [comment]
Most of the tests in https://github.com/Raku/roast/blob/master/integration/gather-with-loops.t do work now.

For strange reasons, the following code does not work as expected. (I'm pretty sure it worked in my branch back in June, so it seems to be something new.):
```
$ ./rakudo-j -e 'say gather for ^3 { take 42; last }'
Exception in thread "main" org.raku.nqp.runtime.UnwindException
        at org.raku.nqp.runtime.ThreadContext.<init>(ThreadContext.java:127)
        at org.raku.nqp.runtime.GlobalContext.getCurrentThreadContext(GlobalContext.java:348)
        at org.raku.nqp.runtime.GlobalContext.<init>(GlobalContext.java:253)
        at org.raku.nqp.runtime.CompilationUnit.enterFromMain(CompilationUnit.java:56)
        at perl6.main(gen/jvm/rakudo.nqp)
```

Using ```next``` or ```redo``` instead of ```last``` does not blow up there.
Also using ```loop``` or ```while 1``` works just fine.
Even using ```&GATHER``` instead of ```gather``` seems to be fine. If I'm not mistaken the explosion happens in ```method pull-one``` in ```Rakudo::Iterator::Gather```:
```
$ ./rakudo-j -e 'my $res := GATHER({ for ^3 { take 42; last } }); my $iter := $res.iterator; say $iter; say $iter.pull-one; say $iter.pull-one'
Rakudo::Iterator::Gather.new
42
IterationEnd
$ ./rakudo-j -e 'my $res := gather for ^3 { take 42; last }; my $iter := $res.iterator; say $iter; say $iter.pull-one; say $iter.pull-one'
Rakudo::Iterator::Gather.new
42
Exception in thread "main" org.raku.nqp.runtime.UnwindException
        at org.raku.nqp.runtime.ThreadContext.<init>(ThreadContext.java:127)
        at org.raku.nqp.runtime.GlobalContext.getCurrentThreadContext(GlobalContext.java:348)
        at org.raku.nqp.runtime.GlobalContext.<init>(GlobalContext.java:253)
        at org.raku.nqp.runtime.CompilationUnit.enterFromMain(CompilationUnit.java:56)
        at perl6.main(gen/jvm/rakudo.nqp)
```

**Comment by usev6** [comment]
I looked some more and it turns out the UnwindException is of category 32 (return). The code doesn't hit the code I changed with https://github.com/Raku/nqp/pull/643. If I'm not mistaken that happens because the for loop is translated to a map operation and therefore takes a different code path than other looping constructs.

Interestingly, if I change the ```LAST``` handler from ```return``` to ```nqp::null``` in method push-all in IterateOneWithoutPhasers (https://github.com/rakudo/rakudo/blob/f0d64ea5e7/src/core.c/Any-iterable-methods.pm6#L451) the explosion goes away.
```
diff --git a/src/core.c/Any-iterable-methods.pm6 b/src/core.c/Any-iterable-methods.pm6
index 9b196297c..ec8b83c4e 100644
--- a/src/core.c/Any-iterable-methods.pm6
+++ b/src/core.c/Any-iterable-methods.pm6
@@ -448,7 +448,7 @@ Consider using a block if any of these are necessary for your mapping code."
                       ),
                       'LABELED', $!label,
                       'REDO', ($redo = 1),
-                      'LAST', return,
+                      'LAST', nqp::null,
                       'NEXT', nqp::null, # need NEXT for next LABEL support
                     )
                   ),
```

As expected, this changes causes other problems (for other tests). But still it might help with figuring out what goes wrong exactly.

**Comment by usev6** [comment]
It looks like this problem has been (unintentionally) 'fixed' with https://github.com/rakudo/rakudo/commit/d8281722db.

All tests in roast's ```integration/gather-with-loops.t``` are passing now.
