### ISSUE TITLE
REPL segmentation fault

### ISSUE THREAD

**Issue by demanuel** [rakudo/rakudo#3678]
## The Problem

I get a segmentation fault on the repl.

## Expected Behavior

I expect not getting a segmentation fault.

## Actual Behavior

I get a segmentation fault.

## Steps to Reproduce

open the raku repl and do:
```
> for ^720 {say ($_/34560*100)}
> 720/48
```

## Environment
* Operating system: 
Linux archlinux 5.6.8-arch1-1 #1 SMP PREEMPT Wed, 29 Apr 2020 16:22:56 +0000 x86_64 GNU/Linux

* Compiler version (`perl6 -v` or `raku -v`): 
This is Rakudo version 2020.05-48-gde173a18c built on MoarVM version 2020.05-4-gc4917b192
implementing Raku 6.d.

**Comment by timo** [comment]
here's some output from gdb:

```Thread 1 "rakudo-m" received signal SIGSEGV, Segmentation fault.
0x00007ffff79e674b in MVM_spesh_frame_walker_move_outer (tc=tc@entry=0x405f60, fw=fw@entry=0x7fffffffe110)
    at src/spesh/frame_walker.c:269
269	        MVMCode *code = (MVMCode *)fw->cur_caller_frame->work[i->code_ref_reg].o;
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.29-28.fc30.x86_64 libzstd-1.4.4-1.fc30.x86_64
(gdb) bt
#0  0x00007ffff79e674b in MVM_spesh_frame_walker_move_outer (tc=tc@entry=0x405f60, fw=fw@entry=0x7fffffffe110)
    at src/spesh/frame_walker.c:269
#1  0x00007ffff799cb43 in apply_traversals (tc=tc@entry=0x405f60, fw=fw@entry=0x7fffffffe110, 
    traversals=traversals@entry=0x39eacc0 "\002\001\236\003", num_traversals=num_traversals@entry=2)
    at src/6model/reprs/MVMContext.c:43
#2  0x00007ffff799d437 in traversal_exists (num_traversals=2, traversals=0x39eacc0 "\002\001\236\003", 
    base=<optimized out>, tc=0x405f60) at src/6model/reprs/MVMContext.c:313
#3  MVM_context_apply_traversal (tc=0x405f60, ctx=<optimized out>, traversal=<optimized out>)
    at src/6model/reprs/MVMContext.c:329
#4  0x00007ffff792bf2a in MVM_interp_run (tc=0x405f60, initial_invoke=0x7fffffffe110, 
    initial_invoke@entry=0x7ffff7a37f40 <toplevel_initial_invoke>, invoke_data=0x7fffffffe110, 
    invoke_data@entry=0x7ffff7a37f40 <toplevel_initial_invoke>, outer_runloop=0xb, outer_runloop@entry=0x0)
    at src/core/interp.c:3348
#5  0x00007ffff7a38f74 in MVM_vm_run_file (instance=instance@entry=0x405450, 
    filename=filename@entry=0x4053f0 "/home/timo/perl6/install/share/perl6/runtime/perl6.moarvm") at src/moar.c:461
#6  0x0000000000401464 in main (argc=<optimized out>, argv=0x7fffffffe6a8) at src/vm/moar/runner/main.c:392
(gdb) call MVM_dump_backtrace(tc)
   at <unknown>:1  (/home/timo/perl6/install/share/nqp/lib/NQPHLL.moarvm:SET_BLOCK_OUTER_CTX)
 from gen/moar/Actions.nqp:1479  (/home/timo/perl6/install/share/perl6/lib/Perl6/Actions.moarvm:lang-version)
 from gen/moar/stage2/QRegex.nqp:1647  (/home/timo/perl6/install/share/nqp/lib/QRegex.moarvm:!reduce)
 from gen/moar/stage2/QRegex.nqp:1590  (/home/timo/perl6/install/share/nqp/lib/QRegex.moarvm:!cursor_pass)
 from gen/moar/Grammar.nqp:867  (/home/timo/perl6/install/share/perl6/lib/Perl6/Grammar.moarvm:lang-version)
 from gen/moar/Grammar.nqp:827  (/home/timo/perl6/install/share/perl6/lib/Perl6/Grammar.moarvm:comp_unit)
 from gen/moar/Grammar.nqp:555  (/home/timo/perl6/install/share/perl6/lib/Perl6/Grammar.moarvm:TOP)
 from gen/moar/stage2/QRegex.nqp:2252  (/home/timo/perl6/install/share/nqp/lib/QRegex.moarvm:parse)
 from gen/moar/stage2/NQPHLL.nqp:2265  (/home/timo/perl6/install/share/nqp/lib/NQPHLL.moarvm:parse)
 from gen/moar/stage2/NQPHLL.nqp:2183  (/home/timo/perl6/install/share/nqp/lib/NQPHLL.moarvm:execute_stage)
 from gen/moar/stage2/NQPHLL.nqp:2216  (/home/timo/perl6/install/share/nqp/lib/NQPHLL.moarvm:run)
 from gen/moar/stage2/NQPHLL.nqp:2208  (/home/timo/perl6/install/share/nqp/lib/NQPHLL.moarvm:)
 from gen/moar/stage2/NQPHLL.nqp:2203  (/home/timo/perl6/install/share/nqp/lib/NQPHLL.moarvm:compile)
 from gen/moar/stage2/NQPHLL.nqp:1886  (/home/timo/perl6/install/share/nqp/lib/NQPHLL.moarvm:eval)
 from SETTING::src/core.c/REPL.pm6:301  (/home/timo/perl6/install/share/perl6/runtime/CORE.c.setting.moarvm:repl-eval)
 from SETTING::src/core.c/REPL.pm6:341  (/home/timo/perl6/install/share/perl6/runtime/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/REPL.pm6:320  (/home/timo/perl6/install/share/perl6/runtime/CORE.c.setting.moarvm:repl-loop)
 from gen/moar/Compiler.nqp:94  (/home/timo/perl6/install/share/perl6/lib/Perl6/Compiler.moarvm:interactive)
 from gen/moar/stage2/NQPHLL.nqp:2034  (/home/timo/perl6/install/share/nqp/lib/NQPHLL.moarvm:command_eval)
 from gen/moar/Compiler.nqp:55  (/home/timo/perl6/install/share/perl6/lib/Perl6/Compiler.moarvm:command_eval)
 from gen/moar/stage2/NQPHLL.nqp:2006  (/home/timo/perl6/install/share/nqp/lib/NQPHLL.moarvm:command_line)
 from gen/moar/rakudo.nqp:127  (/home/timo/perl6/install/share/perl6/runtime/perl6.moarvm:MAIN)
 from gen/moar/rakudo.nqp:92  (/home/timo/perl6/install/share/perl6/runtime/perl6.moarvm:<mainline>)
 from <unknown>:1  (/home/timo/perl6/install/share/perl6/runtime/perl6.moarvm:<main>)
 from <unknown>:1  (/home/timo/perl6/install/share/perl6/runtime/perl6.moarvm:<entry>)
(gdb) list
264	    if (fw->inline_idx == NO_INLINE || !spesh_cand) {
265	        outer = fw->cur_caller_frame->outer;
266	    }
267	    else {
268	        MVMSpeshInline *i = &(spesh_cand->inlines[fw->inline_idx]);
269	        MVMCode *code = (MVMCode *)fw->cur_caller_frame->work[i->code_ref_reg].o;
270	        outer = code ? code->body.outer : NULL;
271	    }
272	    fw->cur_caller_frame = outer;
273	    fw->cur_outer_frame = NULL;
(gdb) info locals 
i = 0x7ffff0088cf0
code = <optimized out>
outer = <optimized out>
spesh_cand = 0x7ffff040f2f0
(gdb) info registers 
rax            0x0                 0
rbx            0x39eacc1           60730561
rcx            0xb                 11
rdx            0x7ffff707ff78      140737337884536
rsi            0x7fffffffe110      140737488347408
rdi            0x405f60            4218720
rbp            0x405f60            0x405f60
rsp            0x7fffffffe0c8      0x7fffffffe0c8
r8             0x1                 1
r9             0x0                 0
r10            0x7ffff7eeebe0      140737353018336
r11            0x7ffff725a250      140737339826768
r12            0x7fffffffe110      140737488347408
r13            0x39eacc2           60730562
r14            0x7fffffffe110      140737488347408
r15            0x1                 1
rip            0x7ffff79e674b      0x7ffff79e674b <MVM_spesh_frame_walker_move_outer+43>
eflags         0x10206             [ PF IF RF ]
cs             0x33                51
ss             0x2b                43
ds             0x0                 0
es             0x0                 0
fs             0x0                 0
gs             0x0                 0
```

**Comment by lizmat** [comment]
Confirmed on MacOS with HEAD

**Comment by demanuel** [comment]
This issue doesn't happen in Comma's REPL.

**Comment by Altai-man** [comment]
FWIW, Comma REPL does not use Rakudo REPL.

**Comment by coke** [comment]
Still happening in a recent rakudo.

**Comment by demanuel** [comment]
This is fixed in the latest master with the new disp merge. :-)
