### ISSUE TITLE
[JVM] Callframes are messed up when recursion creates a deep await-tree

### ISSUE THREAD

**Issue by usev6** [rakudo/rakudo#3816]
## The Problem
The following code (taken from [S17-promise/nonblocking-await.t](https://github.com/Raku/roast/blob/master/S17-promise/nonblocking-await.t), but without really forcing non-blocking await) does not die as expected on the JVM backend:

```
$ ./rakudo-j -e 'sub conc-fib($n) { start { $n <= 1 ?? die "oopsy" !! await(conc-fib($n - 2)) + await(conc-fib($n - 1)) } }; await(conc-fib(15))'
Exception in thread "Thread-1" org.raku.nqp.runtime.UnwindException
        at org.raku.nqp.runtime.ThreadContext.<init>(ThreadContext.java:127)
        at org.raku.nqp.runtime.GlobalContext.getCurrentThreadContext(GlobalContext.java:348)
        at org.raku.nqp.runtime.Ops$CodeRunnable.run(Ops.java:5523)
        at java.base/java.lang.Thread.run(Thread.java:834)
Exception in thread "Thread-3" org.raku.nqp.runtime.UnwindException
        at org.raku.nqp.runtime.ThreadContext.<init>(ThreadContext.java:127)
        at org.raku.nqp.runtime.GlobalContext.getCurrentThreadContext(GlobalContext.java:348)
        at org.raku.nqp.runtime.Ops$CodeRunnable.run(Ops.java:5523)
        at java.base/java.lang.Thread.run(Thread.java:834)
Exception in thread "Thread-4" org.raku.nqp.runtime.UnwindException
        at org.raku.nqp.runtime.ThreadContext.<init>(ThreadContext.java:127)
        at org.raku.nqp.runtime.GlobalContext.getCurrentThreadContext(GlobalContext.java:348)
        at org.raku.nqp.runtime.Ops$CodeRunnable.run(Ops.java:5523)
        at java.base/java.lang.Thread.run(Thread.java:834)
Exception in thread "Thread-5" org.raku.nqp.runtime.UnwindException
        at org.raku.nqp.runtime.ThreadContext.<init>(ThreadContext.java:127)
        at org.raku.nqp.runtime.GlobalContext.getCurrentThreadContext(GlobalContext.java:348)
        at org.raku.nqp.runtime.Ops$CodeRunnable.run(Ops.java:5523)
        at java.base/java.lang.Thread.run(Thread.java:834)
Exception in thread "Thread-6" org.raku.nqp.runtime.UnwindException
        at org.raku.nqp.runtime.ThreadContext.<init>(ThreadContext.java:127)
        at org.raku.nqp.runtime.GlobalContext.getCurrentThreadContext(GlobalContext.java:348)
        at org.raku.nqp.runtime.Ops$CodeRunnable.run(Ops.java:5523)
        at java.base/java.lang.Thread.run(Thread.java:834)
Exception in thread "Thread-7" org.raku.nqp.runtime.UnwindException
        at org.raku.nqp.runtime.ThreadContext.<init>(ThreadContext.java:127)
        at org.raku.nqp.runtime.GlobalContext.getCurrentThreadContext(GlobalContext.java:348)
        at org.raku.nqp.runtime.Ops$CodeRunnable.run(Ops.java:5523)
        at java.base/java.lang.Thread.run(Thread.java:834)
Exception in thread "Thread-8" org.raku.nqp.runtime.UnwindException
        at org.raku.nqp.runtime.ThreadContext.<init>(ThreadContext.java:127)
        at org.raku.nqp.runtime.GlobalContext.getCurrentThreadContext(GlobalContext.java:348)
        at org.raku.nqp.runtime.Ops$CodeRunnable.run(Ops.java:5523)
        at java.base/java.lang.Thread.run(Thread.java:834)
An operation first awaited:
  in block  at -e line 1

Died with the exception:
    Can not invoke object '&die'
      in block  at -e line 1

```

## Expected Behavior
```
$ ./rakudo-m -e 'sub conc-fib($n) { start { $n <= 1 ?? die "oopsy" !! await(conc-fib($n - 2)) + await(conc-fib($n - 1)) } }; await(conc-fib(15))'
An operation first awaited:
  in block  at -e line 1

Died with the exception:
    oopsy
      in block  at -e line 1

```

The following somewhat golfed code shows that there is something wrong with the Callframes, so that ```&die``` can't be found in the second (inner) call of ```foo```. The UnwindException is probably realated to that problem:
```
$ ./rakudo-j -e 'sub foo($n) { say $n; dd OUTER::OUTER::OUTER::.keys; start { $n <= 1 ?? die "oopsy" !! await(foo($n - 1)) } }; await(foo(2))' 2
("CORE-SETTING-REV", "\$/", "\&infix:«(>+)»", "\&infix:<≽>", "\&infix:<≼>", "\$=pod", "\&infix:«(<+)»", "\&await", "\$_", "\$!", "\$¢").Seq
1
().Seq
Exception in thread "Thread-1" org.raku.nqp.runtime.UnwindException
        at org.raku.nqp.runtime.ThreadContext.<init>(ThreadContext.java:127)
        at org.raku.nqp.runtime.GlobalContext.getCurrentThreadContext(GlobalContext.java:348)
        at org.raku.nqp.runtime.Ops$CodeRunnable.run(Ops.java:5523)
        at java.base/java.lang.Thread.run(Thread.java:834)
An operation first awaited:
  in block  at -e line 1

Died with the exception:
    Can not invoke object '&die'
      in block  at -e line 1

```

## Environment
* Operating system: FreeBSD 11.3-RELEASE-p6
* Compiler version (`perl6 -v` or `raku -v`): This is Rakudo version 2020.06-72-g85320f466 built on JVM
implementing Raku 6.d.

**Comment by lizmat** [comment]
Is this still an issue?

**Comment by usev6** [comment]
Unfortunately this problems is still there (same output for the above evaluations with a recent version).
