### ISSUE TITLE
SEGV with a combination of `$_`, `until`, and `andthen`

### ISSUE THREAD

**Issue by MasterDuke17** [rakudo/rakudo#4145]
It golfs to about `($_ = "a: " until .Str) andthen .Str`, which admittedly isn't very sensible, but the code that actually prompted (pun intended) me to try and golf was `sub foo($b) { $_ = ""; ($_ = prompt("$b: ") until .starts-with("y" | "n")) andthen .starts-with("y"); }; say foo("a")`. The original code bisects to https://github.com/rakudo/rakudo/commit/76af17a8b1dc79f8923109bbd284afed2e2fe011 and just timed out before. The golfed code bisects to https://github.com/rakudo/rakudo/commit/8a215876ce037121385f422127a0fe0c630d624c and also just timed out before.

https://gist.github.com/9f3966bd07c71426d021e18e155b4448

https://gist.github.com/f31f058dd46e42eedcfa689cdcc1cead

**Comment by MasterDuke17** [comment]
With MVM_JIT_DISABLE=1 this is the backtrace in gdb:
```
[dan@alexandria perl6]$ MVM_JIT_DISABLE=1 gdb --args ./install/bin/raku -e '($_ = "a" until .starts-with("a")) andthen .Str'
GNU gdb (GDB) 10.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./install/bin/raku...
(gdb) r
Starting program: /home/dan/Source/perl6/install/bin/raku -e \(\$_\ =\ \"a\"\ until\ .starts-with\(\"a\"\)\)\ andthen\ .Str
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff6e05640 (LWP 352557)]

Thread 1 "raku" received signal SIGSEGV, Segmentation fault.
MVM_interp_run (tc=0x555555749df8, initial_invoke=0x0, initial_invoke@entry=0x7ffff79a6680 <toplevel_initial_invoke>, invoke_data=0x0, invoke_data@entry=0x7ffff79a6680 <toplevel_initial_invoke>, outer_runloop=outer_runloop@entry=0x0)
    at src/core/interp.c:6360
6360                    found = GET_LEX(cur_op, 2, f);
(gdb) bt
#0  MVM_interp_run (tc=0x555555749df8, initial_invoke=0x0, initial_invoke@entry=0x7ffff79a6680 <toplevel_initial_invoke>, invoke_data=0x0, invoke_data@entry=0x7ffff79a6680 <toplevel_initial_invoke>, outer_runloop=outer_runloop@entry=0x0)
    at src/core/interp.c:6360
#1  0x00007ffff79a77e4 in MVM_vm_run_file (instance=instance@entry=0x555555559590, filename=filename@entry=0x555555559520 "/home/dan/Source/perl6/install/share/perl6/runtime/perl6.moarvm") at src/moar.c:504
#2  0x00005555555557c4 in main (argc=<optimized out>, argv=0x7fffffffe358) at src/vm/moar/runner/main.c:472
(gdb)
```
With MVM_SPESH_DISABLE=1 it just spins. With MVM_SPESH_PEA_DISABLE=1 and MVM_SPESH_OSR_DISABLE=1 it segfaults, but with MVM_SPESH_INLINE_DISABLE=1 it just spins.

**Comment by MasterDuke17** [comment]
Not sure this will be at all useful, but here's the output with MVM_SPESH_INLINE_LOG:
```
dan@hermes:~/p6$ MVM_SPESH_INLINE_LOG=1 ./install/bin/raku -e '($_ = "a: " until .Str) andthen .Str'
Can inline unspecialized coercive (22) with bytecode size 90 into  (131)
Can NOT inline !find_wrappee (52) with bytecode size 892 into wrappee (53): no spesh candidate available and bytecode too large to produce an inline
Can inline unspecialized wrappee (53) with bytecode size 98 into  (131)
Can inline unspecialized constraint_type (403) with bytecode size 52 into  (131)
Can inline unspecialized  (115) with bytecode size 112 into  (131)
Can inline unspecialized target_type (402) with bytecode size 52 into  (131)
Can NOT inline is_narrower (168) with bytecode size 3008 into  (131): bytecode is too large to inline
Can NOT inline is_bindable (24) with bytecode size 194 into  (133): no spesh candidate available and bytecode too large to produce an inline
Can inline unspecialized add_to_cache (169) with bytecode size 104 into  (133)
Can NOT inline symbol (158) with bytecode size 430 into SET_BLOCK_OUTER_CTX (105): bytecode is too large to inline
Can NOT inline symbol (158) with bytecode size 496 into SET_BLOCK_OUTER_CTX (105): bytecode is too large to inline
Can inline unspecialized is_narrower_type (148) with bytecode size 178 into is_narrower (149)
Can inline unspecialized is_narrower_type (148) with bytecode size 178 into is_narrower (149)
Can inline unspecialized signature (9) with bytecode size 46 into sort_dispatchees (4)
Can inline unspecialized types (11) with bytecode size 46 into sort_dispatchees (4)
Can inline unspecialized definednesses (12) with bytecode size 46 into sort_dispatchees (4)
Can NOT inline is_narrower (149) with bytecode size 1728 into sort_dispatchees (4): bytecode is too large to inline
Can inline unspecialized write_uint32_at (7) with bytecode size 74 into add-internal (158)
Can inline unspecialized write_uint8 (9) with bytecode size 80 into add-internal (158)
Can NOT inline sort_dispatchees (4) with bytecode size 3330 into dispatch (5): bytecode is too large to inline
Can inline is_narrower_type (148) with bytecode size 140 into dispatch (5)
Can inline unspecialized  (2) with bytecode size 90 into  (1920)
Segmentation fault (core dumped)
dan@hermes:~/p6$
```

**Comment by MasterDuke17** [comment]
Some output from rr:
```
dan@hermes:~/p6$ MVM_JIT_DISABLE=1 rr record ./install/bin/raku -e '($_ = "a: " until .Str) andthen .Str'
rr: Saving execution to trace directory `/home/dan/.local/share/rr/raku-0'.
Segmentation fault
dan@hermes:~/p6$ rr replay
GNU gdb (Ubuntu 10.1-2ubuntu2) 10.1.90.20210411-git
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/dan/.local/share/rr/raku-0/mmap_hardlink_3_rakudo...
Really redefine built-in command "restart"? (y or n) [answered Y; input not from terminal]
Remote debugging using 127.0.0.1:48256
Reading symbols from /lib64/ld-linux-x86-64.so.2...
(No debugging symbols found in /lib64/ld-linux-x86-64.so.2)
0x00007f48f52e10d0 in ?? () from /lib64/ld-linux-x86-64.so.2
(rr) continue
Continuing.
[New Thread 48251.48252]

Thread 1 received signal SIGSEGV, Segmentation fault.
MVM_interp_run (tc=0x559a77c37260, initial_invoke=0x0, initial_invoke@entry=0x7f48f4ca8310 <toplevel_initial_invoke>, invoke_data=0x0, invoke_data@entry=0x7f48f4ca8310 <toplevel_initial_invoke>, 
    outer_runloop=outer_runloop@entry=0x0) at src/core/interp.c:6394
6394                    found = GET_LEX(cur_op, 2, f);
(rr) bt
#0  MVM_interp_run (tc=0x559a77c37260, initial_invoke=0x0, initial_invoke@entry=0x7f48f4ca8310 <toplevel_initial_invoke>, invoke_data=0x0, invoke_data@entry=0x7f48f4ca8310 <toplevel_initial_invoke>, 
    outer_runloop=outer_runloop@entry=0x0) at src/core/interp.c:6394
#1  0x00007f48f4ca94b8 in MVM_vm_run_file (instance=instance@entry=0x559a774875c0, filename=filename@entry=0x559a77487550 "/home/dan/Source/perl6/install/share/perl6/runtime/perl6.moarvm") at src/moar.c:504
#2  0x0000559a7721e9e9 in main (argc=<optimized out>, argv=0x7ffdab4f18e8) at src/vm/moar/runner/main.c:472
(rr) p tc->cur_frame
$1 = (MVMFrame *) 0x0
(rr) watch -l tc->cur_frame
Hardware watchpoint 1: -location tc->cur_frame
(rr) reverse-cont
Continuing.

Thread 1 received signal SIGSEGV, Segmentation fault.
MVM_interp_run (tc=0x559a77c37260, initial_invoke=0x0, initial_invoke@entry=0x7f48f4ca8310 <toplevel_initial_invoke>, invoke_data=0x0, invoke_data@entry=0x7f48f4ca8310 <toplevel_initial_invoke>, 
    outer_runloop=outer_runloop@entry=0x0) at src/core/interp.c:6394
6394                    found = GET_LEX(cur_op, 2, f);
(rr) p tc->cur_frame
$2 = (MVMFrame *) 0x0
(rr) reverse-cont
Continuing.

Thread 1 hit Hardware watchpoint 1: -location tc->cur_frame

Old value = (MVMFrame *) 0x0
New value = (MVMFrame *) 0x20000
__memset_avx2_unaligned_erms () at ../sysdeps/x86_64/multiarch/memset-vec-unaligned-erms.S:204
204     ../sysdeps/x86_64/multiarch/memset-vec-unaligned-erms.S: No such file or directory.
(rr) bt
#0  __memset_avx2_unaligned_erms () at ../sysdeps/x86_64/multiarch/memset-vec-unaligned-erms.S:204
#1  0x00007f48f4bcd38b in memset (__len=736, __ch=0, __dest=<optimized out>) at /usr/include/x86_64-linux-gnu/bits/string_fortified.h:59
#2  MVM_fixed_size_alloc_zeroed (tc=tc@entry=0x559a77488100, al=<optimized out>, bytes=bytes@entry=736) at src/core/fixedsizealloc.c:218
#3  0x00007f48f4bb8160 in allocate_frame (tc=tc@entry=0x559a77488100, static_frame=<optimized out>, spesh_cand=<optimized out>, heap=heap@entry=1) at src/core/frame.c:315
#4  0x00007f48f4bb8582 in MVM_frame_invoke (tc=0x559a77488100, static_frame=<optimized out>, callsite=0x7f48f5269660 <null_args_callsite>, args=0x559a7b3ea0f8, outer=<optimized out>, code_ref=<optimized out>, 
    spesh_cand=0) at src/core/frame.c:512
#5  0x00007f48f4c07c64 in invoke_handler (tc=<optimized out>, invokee=<optimized out>, callsite=<optimized out>, args=<optimized out>) at src/6model/reprs/MVMCode.c:10
#6  0x00007f48f4ba2855 in MVM_interp_run (tc=0x559a77c37260, initial_invoke=0x0, initial_invoke@entry=0x7f48f4ca8310 <toplevel_initial_invoke>, invoke_data=0x0, 
    invoke_data@entry=0x7f48f4ca8310 <toplevel_initial_invoke>, outer_runloop=0x559a77c37400, outer_runloop@entry=0x0) at src/core/interp.c:1105
#7  0x00007f48f4ca94b8 in MVM_vm_run_file (instance=instance@entry=0x559a774875c0, filename=filename@entry=0x559a77487550 "/home/dan/Source/perl6/install/share/perl6/runtime/perl6.moarvm") at src/moar.c:504
#8  0x0000559a7721e9e9 in main (argc=<optimized out>, argv=0x7ffdab4f18e8) at src/vm/moar/runner/main.c:472
(rr) f 2
#2  MVM_fixed_size_alloc_zeroed (tc=tc@entry=0x559a77488100, al=<optimized out>, bytes=bytes@entry=736) at src/core/fixedsizealloc.c:218
218         memset(allocd, 0, bytes);
(rr) call MVM_dump_backtrace(tc)
   at SETTING::src/core.c/Rakudo/Iterator.pm6:4775  (/home/dan/Source/perl6/install/share/perl6/runtime/CORE.c.setting.moarvm:pull-one)
 from SETTING::src/core.c/Iterator.pm6:51  (/home/dan/Source/perl6/install/share/perl6/runtime/CORE.c.setting.moarvm:push-all)
 from SETTING::src/core.c/Iterator.pm6:66  (/home/dan/Source/perl6/install/share/perl6/runtime/CORE.c.setting.moarvm:push-until-lazy)
 from SETTING::src/core.c/List.pm6:97  (/home/dan/Source/perl6/install/share/perl6/runtime/CORE.c.setting.moarvm:reify-until-lazy)
 from SETTING::src/core.c/List.pm6:1170  (/home/dan/Source/perl6/install/share/perl6/runtime/CORE.c.setting.moarvm:join)
 from SETTING::src/core.c/List.pm6:367  (/home/dan/Source/perl6/install/share/perl6/runtime/CORE.c.setting.moarvm:Str)
 from SETTING::src/core.c/Sequence.pm6:47  (/home/dan/Source/perl6/install/share/perl6/runtime/CORE.c.setting.moarvm:Str)
 from <unknown>:1  (<ephemeral file>:)
 from SETTING::src/core.c/Rakudo/Iterator.pm6:4781  (/home/dan/Source/perl6/install/share/perl6/runtime/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/Rakudo/Iterator.pm6:4775  (/home/dan/Source/perl6/install/share/perl6/runtime/CORE.c.setting.moarvm:pull-one)
 from SETTING::src/core.c/Iterator.pm6:51  (/home/dan/Source/perl6/install/share/perl6/runtime/CORE.c.setting.moarvm:push-all)
 from SETTING::src/core.c/Iterator.pm6:66  (/home/dan/Source/perl6/install/share/perl6/runtime/CORE.c.setting.moarvm:push-until-lazy)
 from SETTING::src/core.c/List.pm6:97  (/home/dan/Source/perl6/install/share/perl6/runtime/CORE.c.setting.moarvm:reify-until-lazy)
 from SETTING::src/core.c/List.pm6:1171  (/home/dan/Source/perl6/install/share/perl6/runtime/CORE.c.setting.moarvm:join)
 from SETTING::src/core.c/List.pm6:367  (/home/dan/Source/perl6/install/share/perl6/runtime/CORE.c.setting.moarvm:Str)
 from SETTING::src/core.c/Sequence.pm6:47  (/home/dan/Source/perl6/install/share/perl6/runtime/CORE.c.setting.moarvm:Str)
 from <unknown>:1  (<ephemeral file>:)
...
<lots more of the same>
...
 from SETTING::src/core.c/Rakudo/Iterator.pm6:4781  (/home/dan/Source/perl6/install/share/perl6/runtime/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/Rakudo/Iterator.pm6:4778  (/home/dan/Source/perl6/install/share/perl6/runtime/CORE.c.setting.moarvm:pull-one)
 from SETTING::src/core.c/Iterator.pm6:51  (/home/dan/Source/perl6/install/share/perl6/runtime/CORE.c.setting.moarvm:push-all)
 from SETTING::src/core.c/Iterator.pm6:66  (/home/dan/Source/perl6/install/share/perl6/runtime/CORE.c.setting.moarvm:push-until-lazy)
 from SETTING::src/core.c/List.pm6:97  (/home/dan/Source/perl6/install/share/perl6/runtime/CORE.c.setting.moarvm:reify-until-lazy)
 from SETTING::src/core.c/List.pm6:1171  (/home/dan/Source/perl6/install/share/perl6/runtime/CORE.c.setting.moarvm:join)
 from SETTING::src/core.c/List.pm6:367  (/home/dan/Source/perl6/install/share/perl6/runtime/CORE.c.setting.moarvm:Str)
 from SETTING::src/core.c/Sequence.pm6:47  (/home/dan/Source/perl6/install/share/perl6/runtime/CORE.c.setting.moarvm:Str)
 from <unknown>:1  (<ephemeral file>:)
 from SETTING::src/core.c/Rakudo/Iterator.pm6:4781  (/home/dan/Source/perl6/install/share/perl6/runtime/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/Rakudo/Iterator.pm6:4778  (/home/dan/Source/perl6/install/share/perl6/runtime/CORE.c.setting.moarvm:pull-one)
 from SETTING::src/core.c/Iterator.pm6:51  (/home/dan/Source/perl6/install/share/perl6/runtime/CORE.c.setting.moarvm:push-all)
 from SETTING::src/core.c/Iterator.pm6:66  (/home/dan/Source/perl6/install/share/perl6/runtime/CORE.c.setting.moarvm:push-until-lazy)
 from SETTING::src/core.c/List.pm6:97  (/home/dan/Source/perl6/install/share/perl6/runtime/CORE.c.setting.moarvm:reify-until-lazy)
 from SETTING::src/core.c/List.pm6:1171  (/home/dan/Source/perl6/install/share/perl6/runtime/CORE.c.setting.moarvm:join)
 from SETTING::src/core.c/List.pm6:367  (/home/dan/Source/perl6/install/share/perl6/runtime/CORE.c.setting.moarvm:Str)
 from SETTING::src/core.c/Mu.pm6:647  (/home/dan/Source/perl6/install/share/perl6/runtime/CORE.c.setting.moarvm:Str)
 from SETTING::src/core.c/Sequence.pm6:47  (/home/dan/Source/perl6/install/share/perl6/runtime/CORE.c.setting.moarvm:Str)
 from SETTING::src/core.c/Mu.pm6:647  (/home/dan/Source/perl6/install/share/perl6/runtime/CORE.c.setting.moarvm:Str)
 from -e:1  (<ephemeral file>:)
 from SETTING::src/core.c/operators.pm6:349  (/home/dan/Source/perl6/install/share/perl6/runtime/CORE.c.setting.moarvm:infix:<andthen>)
 from SETTING::src/core.c/operators.pm6:343  (/home/dan/Source/perl6/install/share/perl6/runtime/CORE.c.setting.moarvm:infix:<andthen>)
 from -e:1  (<ephemeral file>:<unit>)
 from -e:1  (<ephemeral file>:<unit-outer>)
 from gen/moar/stage2/NQPHLL.nqp:1946  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:eval)
 from gen/moar/stage2/NQPHLL.nqp:2056  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:)
 from gen/moar/stage2/NQPHLL.nqp:2055  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:command_eval)
 from gen/moar/Compiler.nqp:111  (/home/dan/Source/perl6/install/share/perl6/lib/Perl6/Compiler.moarvm:command_eval)
 from gen/moar/stage2/NQPHLL.nqp:2036  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:command_line)
 from gen/moar/rakudo.nqp:127  (/home/dan/Source/perl6/install/share/perl6/runtime/perl6.moarvm:MAIN)
 from gen/moar/rakudo.nqp:1  (/home/dan/Source/perl6/install/share/perl6/runtime/perl6.moarvm:<mainline>)
 from <unknown>:1  (/home/dan/Source/perl6/install/share/perl6/runtime/perl6.moarvm:<main>)
 from <unknown>:1  (/home/dan/Source/perl6/install/share/perl6/runtime/perl6.moarvm:<entry>)
(rr)
```

**Comment by MasterDuke17** [comment]
And then reverse-cont'ing back to the start:
```
(rr) reverse-cont
Continuing.
warning: Corrupted shared library list: 0x559a77d3cec0 != 0x7f48f5314a48

Thread 1 hit Hardware watchpoint 1: -location tc->cur_frame

Old value = (MVMFrame *) 0x20000
New value = (MVMFrame *) 0x0
0x00007f48f4bbd9bb in read_op (val=0x7ffdab4f1080) at src/core/validation.c:170
170         val->labels[pos] |= MVM_BC_op_boundary;
(rr) bt
#0  0x00007f48f4bbd9bb in read_op (val=0x7ffdab4f1080) at src/core/validation.c:170
#1  MVM_validate_static_frame (tc=tc@entry=0x559a77488100, static_frame=0x559a77a45f00) at src/core/validation.c:703
#2  0x00007f48f4bb7390 in prepare_and_verify_static_frame (static_frame=<optimized out>, tc=0x559a77488100) at src/core/frame.c:56
#3  instrumentation_level_barrier (tc=tc@entry=0x559a77488100, static_frame=<optimized out>) at src/core/frame.c:102
#4  0x00007f48f4bb8602 in MVM_frame_invoke (tc=0x559a77488100, static_frame=<optimized out>, callsite=0x7f48f5269660 <null_args_callsite>, args=0x559a77c2c340, outer=<optimized out>, code_ref=<optimized out>, 
    spesh_cand=-1) at src/core/frame.c:408
#5  0x00007f48f4c07c64 in invoke_handler (tc=<optimized out>, invokee=<optimized out>, callsite=<optimized out>, args=<optimized out>) at src/6model/reprs/MVMCode.c:10
#6  0x00007f48f4ba2855 in MVM_interp_run (tc=0x255, tc@entry=0x559a77488100, initial_invoke=0x20, initial_invoke@entry=0x7f48f4ca8310 <toplevel_initial_invoke>, invoke_data=0x20, 
    invoke_data@entry=0x7f48f4ca8310 <toplevel_initial_invoke>, outer_runloop=0x559a77c27f60, outer_runloop@entry=0x0) at src/core/interp.c:1105
#7  0x00007f48f4ca948e in run_deserialization_frame (cu=0x559a77523f40, cu=0x559a77523f40, tc=0x559a77488100) at src/moar.c:483
#8  MVM_vm_run_file (instance=instance@entry=0x559a774875c0, filename=filename@entry=0x559a77487550 "/home/dan/Source/perl6/install/share/perl6/runtime/perl6.moarvm") at src/moar.c:501
#9  0x0000559a7721e9e9 in main (argc=<optimized out>, argv=0x7ffdab4f18e8) at src/vm/moar/runner/main.c:472
(rr) reverse-cont
Continuing.

Thread 1 hit Hardware watchpoint 1: -location tc->cur_frame

Old value = (MVMFrame *) 0x0
New value = <unreadable>
0x00007f48f489cdc9 in __brk (addr=0x559a77c3b000) at ../sysdeps/unix/sysv/linux/brk.c:36
36      ../sysdeps/unix/sysv/linux/brk.c: No such file or directory.
(rr) bt
#0  0x00007f48f489cdc9 in __brk (addr=0x559a77c3b000) at ../sysdeps/unix/sysv/linux/brk.c:36
#1  0x00007f48f489cea4 in __GI___sbrk (increment=<optimized out>) at sbrk.c:74
#2  __GI___sbrk (increment=<optimized out>) at sbrk.c:36
#3  0x00007f48f48288ed in __GI___default_morecore (increment=<optimized out>) at morecore.c:47
#4  0x00007f48f4823552 in sysmalloc (nb=nb@entry=59408, av=av@entry=0x7f48f496fba0 <main_arena>) at malloc.c:2632
#5  0x00007f48f482476f in _int_malloc (av=av@entry=0x7f48f496fba0 <main_arena>, bytes=bytes@entry=59392) at malloc.c:4366
#6  0x00007f48f48262f1 in __GI___libc_malloc (bytes=bytes@entry=59392) at malloc.c:3237
#7  0x00007f48f4be3c74 in MVM_malloc (size=59392) at src/core/alloc.h:2
#8  add_page (bin=1324882077, al=<optimized out>) at src/gc/gen2.c:47
#9  MVM_gc_gen2_allocate (al=<optimized out>, size=size@entry=232) at src/gc/gen2.c:84
#10 0x00007f48f4be3ccc in MVM_gc_gen2_allocate_zeroed (al=<optimized out>, size=232) at src/gc/gen2.c:111
#11 0x00007f48f4bdf801 in MVM_gc_allocate_object (tc=0x559a77488100, st=<optimized out>) at src/gc/allocation.c:93
#12 0x00007f48f4bf6747 in MVM_repr_alloc_init (tc=tc@entry=0x559a77488100, type=<optimized out>) at src/6model/reprconv.c:17
#13 0x00007f48f4bb5b05 in deserialize_frames (rs=0x559a77c0af90, cu=0x559a77524e40, tc=0x559a77488100) at src/core/bytecode.c:495
#14 MVM_bytecode_unpack (tc=tc@entry=0x559a77488100, cu=cu@entry=0x559a77524e40) at src/core/bytecode.c:1020
#15 0x00007f48f4bb3ecb in MVM_cu_from_bytes (tc=tc@entry=0x559a77488100, bytes=bytes@entry=0x7f48f497f000 "MOARVM\r\n\a", size=size@entry=62496) at src/core/compunit.c:21
#16 0x00007f48f4bb3fb8 in MVM_cu_map_from_file (tc=tc@entry=0x559a77488100, filename=filename@entry=0x559a77c0ad00 "/home/dan/Source/perl6/install/share/perl6/lib/Perl6/Ops.moarvm") at src/core/compunit.c:62
#17 0x00007f48f4bc3647 in MVM_load_bytecode (tc=0x559a77488100, filename=<optimized out>) at src/core/loadbytecode.c:106
#18 0x00007f48f4b96ce6 in MVM_interp_run (tc=0x559a77c3b000, tc@entry=0x559a77488100, initial_invoke=0x29000, initial_invoke@entry=0x7f48f4ca8310 <toplevel_initial_invoke>, invoke_data=0x29000, 
    invoke_data@entry=0x7f48f4ca8310 <toplevel_initial_invoke>, outer_runloop=0xe830, outer_runloop@entry=0x0) at src/core/interp.c:3329
#19 0x00007f48f4ca948e in run_deserialization_frame (cu=0x559a77523f40, cu=0x559a77523f40, tc=0x559a77488100) at src/moar.c:483
#20 MVM_vm_run_file (instance=instance@entry=0x559a774875c0, filename=filename@entry=0x559a77487550 "/home/dan/Source/perl6/install/share/perl6/runtime/perl6.moarvm") at src/moar.c:501
#21 0x0000559a7721e9e9 in main (argc=<optimized out>, argv=0x7ffdab4f18e8) at src/vm/moar/runner/main.c:472
(rr) reverse-cont
Continuing.

Thread 1 stopped.
0x00007f48f52e10d0 in ?? () from /lib64/ld-linux-x86-64.so.2
(rr) bt
#0  0x00007f48f52e10d0 in ?? () from /lib64/ld-linux-x86-64.so.2
#1  0x0000000000000003 in ?? ()
#2  0x00007ffdab4f31aa in ?? ()
#3  0x00007ffdab4f31bd in ?? ()
#4  0x00007ffdab4f31c0 in ?? ()
#5  0x0000000000000000 in ?? ()
(rr)
```

**Comment by lizmat** [comment]
In RakuAST the grammar doesn't like it:
```
% RAKUDO_RAKUAST=1 raku -e '($_ = "a: " until .Str) andthen .Str'
===SORRY!===
non-sink statement modifier until NYI
```
