### ISSUE TITLE
Printing in a loop can cause a segfault

### ISSUE THREAD

**Issue by bluebear94** [rakudo/rakudo#4192]
## The Problem

Printing in a loop with enough iterations can cause a segfault:

``` raku
say 0 for ^5000;
print "hi " for ^5000;
```

But these don't seem to cause any problem:

``` raku
0 for ^5000;
my $a = 0; $a++ for ^5000;
```

## Expected Behavior

5000 lines of "0" should be printed to stdout.

## Actual Behavior

The interpreter sometimes encounters a segmentation fault.

## Steps to Reproduce

1. Open up a REPL
2. Run `say 0 for ^5000` twice. Strangely, it only crashes the second time.

Running with the `--ll-exception` flag doesn't give any backtrace.

## Environment
* Operating system: Linux
    ```
    $ uname -a
    Linux elyundite 5.10.7-3-MANJARO #1 SMP PREEMPT Fri Jan 15 21:11:34 UTC 2021 x86_64 GNU/Linux
    ```
* Compiler version (`perl6 -v` or `raku -v`):
    ```
    Welcome to Rakudo(tm) v2020.12.
    Implementing the Raku(tm) programming language v6.d.
    Built on MoarVM version 2020.12.
    ````

**Comment by lizmat** [comment]
This appears to be a REPL artefact.  It runs fine as just code outside of the REPL.

Confirmed on HEAD on MacOS.

Also: you need to enter *anything* after executing the `say 0 for ^5000`, so something internally is messed up after this loop, which causes any subsequent `EVAL` to segfault.

**Comment by lizmat** [comment]
Confirmed that it's `self.compiler.eval()` https://github.com/rakudo/rakudo/blob/master/src/core.c/REPL.pm6#L304 that is segfaulting.

**Comment by bluebear94** [comment]
I found some code that segfaults when run from the command line (using `perl6 -e`):

``` raku
for (1, 2, 3, 4, 5) -> $n { (say $n for ^5000) xx 2 }
```

which also triggers another bug.

**Comment by MasterDuke17** [comment]
With `MVM_JIT_DISABLE=1`:
```
Thread 1 "raku" received signal SIGSEGV, Segmentation fault.
MVM_interp_run (tc=0x555555747bb8, initial_invoke=0x0, initial_invoke@entry=0x7ffff79a58f0 <toplevel_initial_invoke>, invoke_data=0x0, invoke_data@entry=0x7ffff79a58f0 <toplevel_initial_invoke>, outer_runloop=0x1, outer_runloop@entry=0x0)
    at src/core/interp.c:6360
6360                    found = GET_LEX(cur_op, 2, f);
(gdb) bt
#0  MVM_interp_run (tc=0x555555747bb8, initial_invoke=0x0, initial_invoke@entry=0x7ffff79a58f0 <toplevel_initial_invoke>, invoke_data=0x0, invoke_data@entry=0x7ffff79a58f0 <toplevel_initial_invoke>, outer_runloop=0x1, 
    outer_runloop@entry=0x0) at src/core/interp.c:6360
#1  0x00007ffff79a6a54 in MVM_vm_run_file (instance=instance@entry=0x555555559590, filename=filename@entry=0x555555559520 "/home/dan/Source/perl6/install/share/perl6/runtime/perl6.moarvm") at src/moar.c:504
#2  0x00005555555557c4 in main (argc=<optimized out>, argv=0x7fffffffe358) at src/vm/moar/runner/main.c:472
(gdb)
```
No segfault with `MVM_SPESH_DISABLE=1`, `MVM_SPESH_OSR_DISABLE=1`, or `MVM_SPESH_INLINE_DISABLE=1`, but same segfault with `MVM_SPESH_PEA_DISABLE=1`.
```
Welcome to Rakudo(tm) v2020.12-110-g446caae36.
Implementing the Raku(tm) programming language v6.d.
Built on MoarVM version 2020.12-90-g1082d8893.
```
on Arch linux

**Comment by lizmat** [comment]
Golfed to: my $n := 1; (print $n for ^1700) xx 2` which segfaults most of the time on MacOS.

Important elements appear to be:
- must have a variable in the print statement, `print 1` does not segfault
- doesn't matter if using `print`, `say` or `note`
- higher number of iterations makes it likelier to segfault
- the `xx 2` must be there as well

What these two cases appear to have in common, is the use of IO handles for outputting something that is not a constant.

**Comment by MasterDuke17** [comment]
> What these two cases appear to have in common, is the use of IO handles for outputting something that is not a constant.

I can repro the same segfault without IO: `my $n := 1; ($n + 1 for ^17000) xx 20`

**Comment by MasterDuke17** [comment]
Bisectable output, kind of varies across the releases: https://gist.github.com/Whateverable/b6e3e0ddec327643d917c7ab435067dd

**Comment by MasterDuke17** [comment]
Better bisect points to https://github.com/rakudo/rakudo/commit/76af17a8b1dc79f8923109bbd284afed2e2fe011

https://gist.github.com/Whateverable/e9079d808afb717a1242e5168f84688f

**Comment by MasterDuke17** [comment]
Doesn't segfault with raku flag `--optimize=off` (but does with `--optimize=0`)

**Comment by demanuel** [comment]
Isn't this the same (or related) as #3678 ?

**Comment by salortiz** [comment]
FWIW: Prefixing the `for` controlled expression with `do` or creating a block for it, avoids the segfault in all these cases. (The same fixes #4193)

For example:
```raku
my $n := 1; (do $n + 1 for ^17000) xx 20
```

**Comment by demanuel** [comment]
The original issue (the REPL) is fixed in the latest master. 
The issue reported:

> I found some code that segfaults when run from the command line (using `perl6 -e`):
> 
> ```raku
> for (1, 2, 3, 4, 5) -> $n { (say $n for ^5000) xx 2 }
> ```
> 
> which also triggers another bug.

Is still happening.

**Comment by lizmat** [comment]
`for (1, 2, 3, 4, 5) -> $n { (say $n for ^5000) xx 2 }` does **NOT** crash with `MVM_SPESH_DISABLE=1`
