### ISSUE TITLE
SEGV encountered when using Net::IMAP

### ISSUE THREAD

**Issue by Xliff** [rakudo/rakudo#4520]
## The Problem

Encountered SEGV with the following script:

```raku
use Net::IMAP;
my $i = Net::IMAP.new(server => "imap.gmail.com, :ssl, :debug, port => 993\);
$i.say;
$i.authenticate(<my gmail adderss>,  <a gmail password>)
.say for $i.mailboxes;
```

## Actual Behavior

The above code generates a SEGV with the following backtrace:

```
#0  0x00007ffff796c9f4 in get_ptr_at_offset (offset=0, data=0x400) at src/6model/reprs/CStruct.c:367
#1  get_attribute (tc=0x55555555a180, st=<optimized out>, root=<optimized out>, data=0x7ffff484b4c8, class_handle=<optimized out>, name=<optimized out>, 
    hint=-1, result_reg=0x555555877a60, kind=8) at src/6model/reprs/CStruct.c:490
#2  0x00007ffff78f1726 in MVM_interp_run (tc=0x55555555a4e0, initial_invoke=0x400, initial_invoke@entry=0x7ffff79fc4a0 <toplevel_initial_invoke>, 
    invoke_data=0x400, invoke_data@entry=0x7ffff79fc4a0 <toplevel_initial_invoke>, outer_runloop=outer_runloop@entry=0x0) at src/core/interp.c:2195
#3  0x00007ffff79fd66a in MVM_vm_run_file (instance=instance@entry=0x555555559640, 
    filename=filename@entry=0x5555555595b0 "/home/cbwood/Projects/rakudobrew/versions/moar-blead/install/share/perl6/runtime/perl6.moarvm") at src/moar.c:504
#4  0x0000555555555886 in main (argc=<optimized out>, argv=0x7fffffffd848) at src/vm/moar/runner/main.c:474
```

## Environment
$ uname -a
Linux Infinity4 5.11.0-31-generic #33-Ubuntu SMP Wed Aug 11 13:19:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

$ raku --version
Welcome to 𝐑𝐚𝐤𝐮𝐝𝐨™ v2021.08-22-gb451f89b6.
Implementing the 𝐑𝐚𝐤𝐮™ programming language v6.d.
Built on MoarVM version 2021.08-9-g4b7ffe3af.

**Comment by jonathanstowe** [comment]
It's the  `$i.say` that is provoking the segv, I suspect that it's due to the implicit `.gist` on the IO::Socket::SSL object.  Without that line it works. 

Valgrind output with the `say`:

```
================================================================================================
This is Rakudo running in valgrind, a tool for debugging and profiling programs.
Running a program in valgrind usually takes *a lot* more time than running it directly,
so please be patient.
Valgrind options can be added with MVM_VALGRIND_OPTS environment variable.

This Rakudo version is 2021.08.20.g.57841911.f built on MoarVM version 2021.08.9.g.4.b.7.ffe.3.af,
running on fedora (34.Workstation.Edition) / linux
------------------------------------------------------------------------------------------------
==563651== Memcheck, a memory error detector
==563651== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==563651== Using Valgrind-3.17.0 and LibVEX; rerun with -h for copyright info
==563651== Command: /usr/local/bin/rakudo-m -I. xx
==563651== 
==563651== Invalid read of size 8
==563651==    at 0x4AD3562: get_attribute (in /usr/local/lib/libmoar.so)
==563651==    by 0x4A5D49B: MVM_interp_run (in /usr/local/lib/libmoar.so)
==563651==    by 0x4016E8: main (in /usr/local/bin/rakudo-m)
==563651==  Address 0x400 is not stack'd, malloc'd or (recently) free'd
==563651== 
==563651== 
==563651== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==563651==  Access not within mapped region at address 0x400
==563651==    at 0x4AD3562: get_attribute (in /usr/local/lib/libmoar.so)
==563651==    by 0x4A5D49B: MVM_interp_run (in /usr/local/lib/libmoar.so)
==563651==    by 0x4016E8: main (in /usr/local/bin/rakudo-m)
==563651==  If you believe this happened as a result of a stack
==563651==  overflow in your program's main thread (unlikely but
==563651==  possible), you can try to increase the size of the
==563651==  main thread stack using the --main-stacksize= flag.
==563651==  The main thread stack size used in this run was 8388608.
==563651== 
==563651== Process terminating with default action of signal 11 (SIGSEGV)
==563651==  General Protection Fault
==563651==    at 0x545AC82: __pthread_once_slow (in /usr/lib64/libpthread-2.33.so)
==563651==    by 0x526703E: __rpc_thread_variables.part.0 (in /usr/lib64/libc-2.33.so)
==563651==    by 0x52A961C: free_mem (in /usr/lib64/libc-2.33.so)
==563651==    by 0x52A9271: __libc_freeres (in /usr/lib64/libc-2.33.so)
==563651==    by 0x48351E7: _vgnU_freeres (vg_preloaded.c:74)
==563651==    by 0xBB0916F: ???
==563651==    by 0x5B81ECF: ???
==563651==    by 0xCE1EB87: ???
==563651==    by 0x5B832BF: ???
==563651== 
==563651== HEAP SUMMARY:
==563651==     in use at exit: 81,826,340 bytes in 280,179 blocks
==563651==   total heap usage: 505,545 allocs, 225,366 frees, 287,192,563 bytes allocated
==563651== 
==563651== LEAK SUMMARY:
==563651==    definitely lost: 35,171 bytes in 565 blocks
==563651==    indirectly lost: 97,620 bytes in 1,880 blocks
==563651==      possibly lost: 3,927,448 bytes in 673 blocks
==563651==    still reachable: 77,766,101 bytes in 277,061 blocks
==563651==         suppressed: 0 bytes in 0 blocks
==563651== Rerun with --leak-check=full to see details of leaked memory
==563651== 
==563651== For lists of detected and suppressed errors, rerun with: -s
==563651== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
/usr/local/bin/rakudo-valgrind-m: line 53: 563651 Segmentation fault      (core dumped) "$VALGRIND" ${MVM_VALGRIND_OPTS} "$DIR/rakudo-m" "$@"
```

I suspect that somewhere in `IO::Socket::SSL` there is a struct with a member that is specified at the wrong size which never gets accessed in normal circumstances.

**Comment by Xliff** [comment]
Thanks, @jonathanstowe. I will create a bug report on the IO::Socket:SSL page and will reference this issue.
