### ISSUE TITLE
Random failures for t/02-rakudo/15-gh_1202.t

### ISSUE THREAD

**Issue by usev6** [rakudo/rakudo#4588]
The first test in [t/02-rakudo/15-gh_1202.t](https://github.com/rakudo/rakudo/blob/master/t/02-rakudo/15-gh_1202.t) randomly fails. This problem is also noted in https://github.com/rakudo/rakudo/issues/4212, a meta issue about flapping tests.

There was quite some discussion on [the IRC channel #moarvm](https://colabti.org/irclogger/irclogger_log/moarvm), I'm gathering some information here.

According to https://colabti.org/irclogger/irclogger_log/moarvm?date=2021-08-12#l117 it is enough to run the following command for a while to reproduce the problem:
```
$ while ./rakudo-m -Ilib t/02-rakudo/15-gh_1202.t; do :; done
[...]
not ok 1 - shell output
# Failed test 'shell output'
# at t/02-rakudo/15-gh_1202.t line 18
# expected a match with: /[ <[0..4]> \n ] ** 250/
#                   got: "0\n2\n3\n1\n4\n1\n0\n2\n4\n3\n0\n2\n3\n4\n1\n1\n0\n2\n3\n4\n2\n1\n0\n3\n4\n4\n1\n2\n0\n3\n0\n1\n2\n3\n4\n0\n3\n4\n1\n2\n0\n2\n3\n1\n4\n0\n1\n3\n4\n2\n0\n1\n2\n3\n4\n3\n0\n1\n4\n2\n1\n2\n0\n4\n3\n3\n1\n4\n0\n2\n1\n0\n3\n4\n2\n3\n2\n4\n0\n1\n0\n1\n4\n2\n3\n4\n3\n0\n2\n1\n2\n3\n0\n4\n1\n3\n0\n4\n2\n1\n2\n3\n1\n4\n0\n1\n2\n0\n3\n4\n1\n4\n3\n0\n2\n2\n4\n0\n1\n3\n1\n4\n3\n0\n2\n1\n0\n2\n3\n4\n0\n1\n4\n3\n2\n4\n3\n1\n2\n0\n0\n4\n1\n3\n2\n2\n3\n1\n4\n0\n1\n3\n2\n0\n4\n4\n1\n2\n3\n0\n1\n2\n3\n0\n4\n2\n1\n4\n3\n0\n2\n1\n0\n4\n3\n2\n4\n0\n1\n3\n1\n2\n3\n0\n4\n2\n3\n0\n4\n1\n4\n1\n0\n3\n2\n2\n3\n1\n4\n0\n2\n3\n1\n0\n4\n1\n2\n3\n0\n4\n2\n0\n3\n1\n4\n1\n4\n2\n3\n0\n3\n2\n0\n4\n1\n0\n1\n2\n3\n4\n2\n3\n4\n1\n0\n2\n3\n0\n1\n4\n2\n3\n1\n4\n0\n"
ok 2 - all runs completed
# You failed 1 test of 2
```
The output contains 245 lines instead of the expected 250.

Adding a ```MVM_SPESH_NODELAY=1``` seems to make the test failure more likely (source: https://colabti.org/irclogger/irclogger_log/moarvm?date=2021-10-05#l98)

The test failure seems to be caused by a crash in one of the forked processes. According to https://colabti.org/irclogger/irclogger_log/moarvm?date=2021-10-03#l112 there seem to be two different failure modes:

> either a SEGV or with 'MoarVM panic: Memory allocation failed; could not allocate 29035875272 bytes'
> it's always the same number

Here @dogbert17++ caught the problem with gdb:   https://colabti.org/irclogger/irclogger_log/moarvm?date=2021-10-02#l125
> #0 0x00007fc2097e58e4 in MVM_disp_program_run (tc=tc@entry=0x7fc1f01c6fb0, dp=0x55e977d11770, record=record@entry=0x7fc1e0063870, spesh_cid=spesh_cid@entry=0, bytecode_offset=bytecode_offset@entry=200,
> dp_index=dp_index@entry=3) at src/disp/program.c:2933
> 2933 if (STABLE(val.o) != (MVMSTable *)dp->gc_constants[op.arg_guard.checkee])
> (gdb) p val
> $3 = {o = 0x0, s = 0x0, i8 = 0 '\000', u8 = 0 '\000', i16 = 0, u16 = 0, i32 = 0, u32 = 0, i64 = 0, u64 = 0, n32 = 0, n64 = 0}
> (gdb) f 1
> #1  0x00007f73a8fbcc0f in dispatch_polymorphic (tc=0x7f73940fc0f0,  entry_ptr=0x55b8b00253e8, seen=0x55b8b0c06868, id=0x55b8afa1c0b0,  callsite=0x55b8ad89c7c0, arg_indices=0x7f73a5895286,
> source=0x7f738009d0d0, sf=0x55b8afa17610, bytecode_offset=200) at src/disp/inline_cache.c:178
> 178 MVMROOT2(tc, id, sf, {

**Comment by usev6** [comment]
There was another mention of the failures with t/02-rakudo/15-gh_1202 in #raku-dev last week: https://colabti.org/irclogger/irclogger_log/raku-dev?date=2022-01-14#l161, referring to https://github.com/rakudo/rakudo/commit/768ebea783 as a possible fix for (most of?) the failures.

**Comment by niner** [comment]
Unfortunately it failed yet again on s390: https://build.opensuse.org/public/build/home:niner9:rakudo-git/openSUSE_Factory_zSystems/s390x/rakudo/_log
Seems like this test somehow manages to trigger a multitude of bugs. There's also still the expr JIT issue, but that can only affect x86_64.

**Comment by lizmat** [comment]
Is this still an issue, now that the expression JIT is disabled by default?

**Comment by dogbert17** [comment]
Yes, there's a GC related bug hiding there.

Den tors 17 okt. 2024 kl 18:42 skrev Elizabeth Mattijsen <
***@***.***>:
