### ISSUE TITLE
[JVM] SaveStackException when calling hyper on List and nqp::continuationcontrol gets called more than once

### ISSUE THREAD

**Issue by usev6** [rakudo/rakudo#5438]
## The Problem
The following code often (but not always) spits out an internal error on the JVM backend:
```
$ ./rakudo-j -e 'say (^10).hyper; say "alive"'; echo $?
Exception in thread "Thread-1" org.raku.nqp.runtime.SaveStackException
        at org.raku.nqp.runtime.Ops.continuationcontrol(Unknown Source)
        at 3C40A41704D71F91F3F8B123B77ACB0410B670AB.qb_15341(gen/jvm/CORE.c.setting:8103)
        at 3C40A41704D71F91F3F8B123B77ACB0410B670AB.qb_15342(gen/jvm/CORE.c.setting:8095)
        at org.raku.nqp.runtime.ArgsExpectation.invokeByExpectation(Unknown Source)
        at org.raku.nqp.runtime.IndyBootstrap.indcallInvoker_noa(Unknown Source)
        at 3C40A41704D71F91F3F8B123B77ACB0410B670AB.qb_15337(gen/jvm/CORE.c.setting:8087)
        at org.raku.nqp.runtime.ArgsExpectation.invokeByExpectation(Unknown Source)
        at org.raku.nqp.runtime.IndyBootstrap.methcallCacheMono_noa(Unknown Source)
        at 3C40A41704D71F91F3F8B123B77ACB0410B670AB.qb_5145(gen/jvm/CORE.c.setting:29162)
        at org.raku.nqp.runtime.ResumeStatus$Frame.resume(Unknown Source)
        at org.raku.nqp.runtime.ResumeStatus$Frame.resumeNext(Unknown Source)
        at org.raku.nqp.runtime.ResumeStatus$Frame.resumeNextSave(Unknown Source)
        at 3C40A41704D71F91F3F8B123B77ACB0410B670AB.qb_15615(gen/jvm/CORE.c.setting:9587)
        at org.raku.nqp.runtime.ResumeStatus$Frame.resume(Unknown Source)
        at org.raku.nqp.runtime.ResumeStatus$Frame.resumeNext(Unknown Source)
        at org.raku.nqp.runtime.ResumeStatus$Frame.resumeNextSave(Unknown Source)
        at 3C40A41704D71F91F3F8B123B77ACB0410B670AB.qb_15470(gen/jvm/CORE.c.setting:8937)
        at org.raku.nqp.runtime.ResumeStatus$Frame.resume(Unknown Source)
        at org.raku.nqp.runtime.ResumeStatus$Frame.resumeNext(Unknown Source)
        at org.raku.nqp.runtime.ResumeStatus$Frame.resumeNextSave(Unknown Source)
        at 3C40A41704D71F91F3F8B123B77ACB0410B670AB.qb_15375(gen/jvm/CORE.c.setting:8304)
        at org.raku.nqp.runtime.ResumeStatus$Frame.resume(Unknown Source)
        at org.raku.nqp.runtime.ResumeStatus$Frame.resumeNext(Unknown Source)
        at org.raku.nqp.runtime.ResumeStatus$Frame.resumeNextSave(Unknown Source)
        at 3C40A41704D71F91F3F8B123B77ACB0410B670AB.qb_15376(gen/jvm/CORE.c.setting:8299)
        at org.raku.nqp.runtime.ResumeStatus$Frame.resume(Unknown Source)
        at org.raku.nqp.runtime.Ops.continuationinvoke(Unknown Source)
        at 3C40A41704D71F91F3F8B123B77ACB0410B670AB.qb_15369(gen/jvm/CORE.c.setting:8282)
        at 3C40A41704D71F91F3F8B123B77ACB0410B670AB.qb_15378(gen/jvm/CORE.c.setting:8281)
        at org.raku.nqp.runtime.ArgsExpectation.invokeByExpectation(Unknown Source)
        at org.raku.nqp.runtime.IndyBootstrap.indcallInvoker_noa(Unknown Source)
        at 3C40A41704D71F91F3F8B123B77ACB0410B670AB.qb_15383(gen/jvm/CORE.c.setting:8323)
        at org.raku.nqp.runtime.ArgsExpectation.invokeByExpectation(Unknown Source)
        at org.raku.nqp.runtime.IndyBootstrap.subcallResolve_noa(Unknown Source)
        at 3C40A41704D71F91F3F8B123B77ACB0410B670AB.qb_15120(gen/jvm/CORE.c.setting:7149)
        at org.raku.nqp.runtime.ArgsExpectation.invokeByExpectation(Unknown Source)
        at org.raku.nqp.runtime.Ops.invokeDirect(Unknown Source)
        at org.raku.nqp.runtime.Ops.invokeDirect(Unknown Source)
        at org.raku.nqp.runtime.Ops.invokeArgless(Unknown Source)
        at org.raku.nqp.runtime.Ops$CodeRunnable.run(Unknown Source)
        at java.base/java.lang.Thread.run(Thread.java:829)
(0 1 2 3 4 5 6 7 8 9)
alive
0
```

Please note that the evaluation doesn't fail.

## Expected Behavior
There should be no error output at all.
```
$ ./rakudo-m -e 'say (^10).hyper; say "alive"'; echo $?
(0 1 2 3 4 5 6 7 8 9)
alive
0
```

## Additional Information
If I'm not mistaken the message about a SaveStackException appears if ```nqp::continuationcontrol``` is called more than once.

The stack trace points to ```method !do-await``` in ```class ThreadPoolAwaiter```: https://github.com/rakudo/rakudo/blob/bd5a28c904/src/core.c/ThreadPoolScheduler.rakumod#L65

## Environment
* Operating system: FreeBSD 13.2-RELEASE-p2
* Compiler version (`rakudo -v` or `raku -v`): Welcome to Rakudo™ v2023.10-13-gfe8123d04.

**Comment by usev6** [comment]
I noticed that adding ```sleep 1``` after the call to ```hyper``` made the error message show up every time (and seemingly ```nqp::continuationcontrol``` always got called twice). So probably the "missing" error was due to the program already being ended before the second call.
